### PR TITLE
Fix saga error should not result in unhandled exception

### LINKED ISSUE #2420: When saga error occurred, it should not turn into disconnect
## Version

`master`

## Describe the bug

There are two problems:

- When saga error, it disconnect Direct Line. Connectivity status turn from "sagaerror" to "disconnected"
- But since there is a bug in "disconnected" reducer, an exception prevented "sagaerror" turn into "disconnected", but result in an exception

## To Reproduce

1. Open playground
1. Click "Inject error"

## Expected behavior

Check console log, there should be no exception other than the saga error. And the connectivity status should say, "Render error. Please check the console or contact the bot developer."

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #2420

### Fixed

-  Fix [#2420](https://github.com/microsoft/BotFramework-WebChat/issues/2420). Fix saga error should not result in an unhandled exception, by [@compulim](https://github.com/compulim) in PR [#2421](https://github.com/microsoft/BotFramework-WebChat/pull/2421)

## Description

Saga error is currently resulted in unhandled exception. Once that is fixed, it become disconnected, instead of keeping at saga error.

## Specific Changes

- Modified `connectivityStatus.js`
   - Fixed null reference exception
   - Should not change connectivity status once it become `sagaerror`

---

-  [x] ~Testing Added~
   - We currently do not have tests to check how many console errors

### CODE REVIEW

File: packages/core/src/reducers/connectivityStatus.js [hunk 1]
```diff
@@ -8,41 +8,43 @@ import { SAGA_ERROR } from '../actions/sagaError';
...
-      state = meta.error ? 'error' : 'notconnected';
-      break;
-
-    case SAGA_ERROR:
-      state = 'sagaerror';
-      break;
-
-    default:
-      break;
+  if (state !== 'sagaerror') {
```
Comment (tdurnford) [inline packages/core/src/reducers/connectivityStatus.js]: Haha well that was easy

**Comment by compulim** [comment]
> https://webchattest.blob.core.windows.net/travis-result/2019/09/22/71xj9/__image_snapshots__/chrome-docker/__diff_output__/offline-ui-js-offline-ui-should-display-network-interruption-occurred-reconnecting-status-when-connection-is-interrupted-1-diff.png
> 
> Test is failing

Yap, was working on this yesterday. It works on my PC. 🤔

**Comment by corinagum** [comment]
Ping

**Comment by corinagum** [comment]
ping...

**Comment by tdurnford** [comment]
ping...
