### PR TITLE
Fix text missing after HTML tags

### LINKED ISSUE #5319: Some Markdown after HTML tags are not rendered
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Development build

### Which distribution are you using Web Chat from?

Unrelated

### Which hosting environment does this issue primarily affect?

Others or unrelated

### Which browsers and platforms do the issue happened?

Others or unrelated

### Which area does this issue affect?

Chat history

### Which theme pack does this issue affect?

I did not test it on other theme packs

### What is the public URL for the website?

_No response_

### Please describe the bug

The following Markdown is not rendered properly:

```md
Line 1

<br />
Line 2
```

From CommonMark Dingus, it would output:

```
<p>Line 1</p>
<br />
Line 2
```

Note: "Line 2" is a text node and is not wrapped in `<p>`. This is expected.

### Do you see any errors in console log?

```js
No.
```

### How to reproduce the issue?

Bot send the following Markdown message.

```md
Line 1

<br />
Line 2
```

### What do you expect?

It renders with both "Line 1" and "Line 2".

```html
<p>Line 1</p><br />Line 2
```

### What actually happened?

It renders without "Line 2".

```html
<p>Line 1</p><br />
```

### Do you have any screenshots or recordings to repro the issue?

image

### Adaptive Card JSON

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #5319.

### Fixed

-  Fixes [#5319](https://github.com/microsoft/BotFramework-WebChat/issues/5319). Some Markdown text are not rendered after HTML tags, in PR [#5320](https://github.com/microsoft/BotFramework-WebChat/pull/5320), by [@compulim](https://github.com/compulim)

## Description

Our HTML parsing and serialization logic only handle `.children` but not `.childNodes`. Thus, it is omitting text nodes.

When dealing with certain types of Markdown, the text may not be wrapped in `<p>`. For example,

```md
Line 1

<br />
Line 2
```

Will be converted to HTML and "Line 2" is not wrapped in `<p>`:

```html
<p>Line 1</p><br />Line 2
```

## Specific Changes

- Updates `serializeDocumentIntoString` and `useRenderMarkdownAsHTML` to handle text nodes

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [x] ~Accessibility reviewed (tab order, content readability, alt text, color contrast)~
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

**Review by OEvgeny — APPROVED** [review]

File: packages/component/src/Utils/parseDocumentFragmentFromString.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export default function parseDocumentFragmentFromString(html: string): DocumentFragment {
+  const parser = new DOMParser();
+  const fragment = new DocumentFragment();
+
+  fragment.append(...parser.parseFromString(html, 'text/html').body.childNodes);
+
+  return fragment;
```
Comment (OEvgeny) [inline packages/component/src/Utils/parseDocumentFragmentFromString.ts:7]:
```suggestion
  const parser = new DOMParser();
  const parsedDocument = parser.parseFromString(html, 'text/html'
  const fragment = parsedDocument.createDocumentFragment();

  fragment.append(parsedDocument.body.childNodes);

  return fragment;
```
If we want to save the `parsedDocument` ownership of any element added to the fragment.

Comment (compulim) [reply packages/component/src/Utils/parseDocumentFragmentFromString.ts:7]: This works much better... my previous code will run `onload` script. 🙈

Good that we have test. 😉

**Review by OEvgeny — APPROVED** [review]

**Review by OEvgeny — APPROVED** [review]
