### PR TITLE
Fix #1602: suggested-action regression 

### LINKED ISSUE #1602: Quotation marks around suggested action
Hey,

when using the "master" branch, the suggested actions are suddenly surrounded by quotation marks. The functionality is the same, it's just a style issue.

image

### PR DESCRIPTION
**Pull request by corinagum**
Fixes #1602 
`title` was not getting added to `postback` and `imback` action buttons.
- Also added an integration test to prevent this from happening in the future :)

### CODE REVIEW

File: packages/component/src/SendBox/SuggestedActions.js [hunk 1]
```diff
@@ -48,8 +48,11 @@ export default connectSuggestedActions(
             buttonText={
               type === 'messageBack' ?
                 title || displayText
-              :
-                title || (typeof value !== 'string') ? JSON.stringify(value) : value
+              : title ?
+                  title
+                : (typeof value === 'string') ?
```
Comment (compulim) [inline packages/component/src/SendBox/SuggestedActions.js]: The indentation looks a bit weird to me.

File: __tests__/suggestedActions.js [hunk 2]
```diff
@@ -9,6 +9,20 @@ function sleep(ms = 1000) {
 // https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_WebDriver.html
 
 describe('suggested-actions command', async () => {
+    test('should show correctly formatted buttons when suggested actions are displayed', async() => {
```
Comment (compulim) [inline __tests__/suggestedActions.js]: Can you change it from 4-space to 2-space? You find my VSCode extension to do the job.

File: packages/component/src/SendBox/SuggestedActions.js (hunk 1 above)
Comment (a-b-r-o-w-n) [reply packages/component/src/SendBox/SuggestedActions.js]: Not only that, but a nested ternary is usually avoided. Maybe this can be extracted into a utility function and re-written as an if / else

**Comment by corinagum** [comment]
ping @compulim @a-b-r-o-w-n, please let me know what you think about the changes :)

File: packages/component/src/SendBox/SuggestedActions.js [hunk 3]
```diff
@@ -5,6 +5,18 @@ import React from 'react';
 import connectToWebChat from '../connectToWebChat';
 import SuggestedAction from './SuggestedAction';
 
+function renderSuggestedAction ({title, type, value}) {
+  if(type === 'messageBack') {
+    return title || displayText
```
Comment (a-b-r-o-w-n) [inline packages/component/src/SendBox/SuggestedActions.js]: `displayText` is undefined here right?

File: packages/component/src/SendBox/SuggestedActions.js [hunk 4]
```diff
@@ -5,6 +5,18 @@ import React from 'react';
 import connectToWebChat from '../connectToWebChat';
 import SuggestedAction from './SuggestedAction';
 
+function renderSuggestedAction ({title, type, value}) {
+  if(type === 'messageBack') {
```
Comment (a-b-r-o-w-n) [inline packages/component/src/SendBox/SuggestedActions.js]: nit: space between `if` and `(`

File: packages/component/src/SendBox/SuggestedActions.js [hunk 5]
```diff
@@ -46,10 +58,7 @@ export default connectSuggestedActions(
         ) =>
           <SuggestedAction
             buttonText={
-              type === 'messageBack' ?
-                title || displayText
-              :
-                title || (typeof value !== 'string') ? JSON.stringify(value) : value
+             renderSuggestedAction({title, type, value})
```
Comment (a-b-r-o-w-n) [inline packages/component/src/SendBox/SuggestedActions.js]: A comment about the naming of this function: when I see `renderBlah` I expect that function to return some jsx. In this case it just returns a string, so I would suggest renaming to something like `suggestedActionText`.

File: packages/component/src/SendBox/SuggestedActions.js (hunk 3 above)
Comment (corinagum) [reply packages/component/src/SendBox/SuggestedActions.js]: oops thanks for the catch

**Comment by corinagum** [comment]
@a-b-r-o-w-n @compulim ping :)

File: packages/component/src/SendBox/SuggestedActions.js [hunk 6]
```diff
@@ -46,10 +58,7 @@ export default connectSuggestedActions(
         ) =>
           <SuggestedAction
             buttonText={
-              type === 'messageBack' ?
-                title || displayText
-              :
-                title || (typeof value !== 'string') ? JSON.stringify(value) : value
+             suggestedActionText({displayText, title, type, value})
```
Comment (compulim) [inline packages/component/src/SendBox/SuggestedActions.js]: Formatting: parenthesis between bracelets.

```suggestion
             suggestedActionText({ displayText, title, type, value })
```

File: packages/component/src/SendBox/SuggestedActions.js [hunk 7]
```diff
@@ -5,6 +5,18 @@ import React from 'react';
 import connectToWebChat from '../connectToWebChat';
 import SuggestedAction from './SuggestedAction';
 
+function suggestedActionText ({displayText, title, type, value}) {
```
Comment (compulim) [inline packages/component/src/SendBox/SuggestedActions.js]: Code formatting.

```suggestion
function suggestedActionText({ displayText, title, type, value }) {
```
