### PR TITLE
Converge suggested actions into live region twin and add roving tab index

### LINKED ISSUE #4293: [Screen Readers-Ask HR Virtual Assistant]: Screen readers(NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.
### PWD Impact:
Screen reader users are getting impacted if Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window. 

### Test Environment:

OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 92.0.902.62 (Official build) (64-bit)/Chrome Version 92.0.4515.107 (Official Build) (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvadev.azureedge.net/?botOrigin=ec)
Tools: NVDA 2021.1/JAWS 2021.2105.53 ILM 

### Repro Steps:
Step 1: Enable Screen readers (NVDA/JAWS) and open the above URL in the Chrome/Edge Browser using valid credentials.
Step 2: 'AskHR Virtual Assistant' Home page gets opened.
Step 3: Navigate to the list items suggestions using down arrow key and select Benefits verify the screen readers (NVDA/JAWS) behavior upon invoking the suggestion questionnaire button present in the “Ask HR Virtual Assistant” chat window. 

### Actual Result:
Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS narrating as "Suggested Actions Container: Is empty………………………………complementary landmark form landmark form landmark message input box edit type your message blank Suggested Actions Container: Has content Press Alt+ Shift + A to select Laya Pension (Mercer)Well being program ESPP other benefits None of these/ask a different question "

### Expected Result:
Screen readers(NVDA/JAWS) shouldn't narrate the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS should narrate as "Select an option to continue this conversation Suggested Actions Container: Has content  Press Alt+ Shift + A to select 6 list items button Laya, button Pension(Mercer), button Well being program, button  ESPP, button  other benefits, button None of these/ask a different question"

### MAS Reference:
[MAS 4.2.1 – Object Information](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7bEEE97BBD-9990-48A0-8B03-6EA775581AA8%7d&file=MAS%204.2.1%20%E2%80%93%20Object%20Information.docx&wdLOR=cBC823FF2-F30B-4029-A49F-90FCC0AB9FEB&action=default&mobileredirect=true)

### LINKED ISSUE #4296: [Screen Readers-Ask HR Bot-Ask HR Virtual Assistant]: NVDA is not narrating proper information if user invokes the Suggested questionnaire buttons from the list present in the page.
### PWD Impact:
Screen reader users are getting impacted if once the user invokes the suggested questionnaire buttons in the page and screen reader is not narrating the invoked button information.

### Test Environment:
OS: WIN10 1909 (OS Build 18363.836)
Browser: New Edge Version 83.0.478.37 (Official build) (64-bit)
URL: [https://microsoft.sharepoint.com/teams/HR_Web_Dev_Site/SitePages/AskHRBotTest.aspx](https://microsoft.sharepoint.com/teams/HR_Web_Dev_Site/SitePages/AskHRBotTest.aspx?xsdata=MDV8MDF8fGUwOGNmNzIxMWMwMDRlNmFlMDA0MDhkYTNjYzAzZjJmfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzc4ODkwOTM2MTc4MzYwMzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2TjJRd1lqVXpZell0TWpBNVlTMDBNVGhqTFdFM09XUXRNMlJqWVdOaU4yUTJORFUyWDJNd1lqazJZalZrTFROaE1EQXROR1l6WVMwNVpXRXhMVFZoTVdZell6RTNZVEZoWTBCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=bkFwYTdYNWp3dnEzcmp2aW1aaTJiQXZnTVhpMWtzVFNuOEdFWm5kR0p0Yz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-kbhargav%40microsoft.com)
Screen Reader: NVDA 2019.3.1

### Repro Steps:
Step 1: Enable NVDA and open the above URL in New Edge browser.
Step 2: Navigate to the “Ask HR Bot” Button in browse mode and invoke it.
Step 3: Chat window of “ASK HR Bot” is displayed on the screen.
Step 4: Verify the screen reader behavior upon invoking the Suggested questionnaire button in the page.

### Actual Result:
NVDA is not narrating proper information if user invokes the Suggested questionnaire buttons from the list present in the page.
**Ex:** NVDA is narrating the previous information of what Bot Said  which is already present upon invoking the "As a Generic Question" button in the chat box.

### Expected Result:
NVDA should narrate the proper information if user invokes the  Suggested questionnaire button from the list present at the bottom of the chat box.
**Ex:** Once user invokes “Ask a Generic Question” suggestion button then NVDA should narrate as Puneet Said Ask a Generic Question then with next Down arrow NVDA should narrate the suggestion provided from BOT .
**Ensure that:** If user ask a different question like “Leave/Time Away” then many suggestions appear on the screen NVDA should also narrate the information of the suggestions correctly while navigating in NVDA browse

### MAS Reference:
[MAS 4.2.1 - Object Information (33A)](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7Ba12f3779-bdf1-40c2-bbcc-0e314ea94858%7D&xsdata=MDV8MDF8fDEzODRhOWY4ODJjYTRmZTdlMDA0MDhkYTNjYzAzZjJmfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzc4ODkwOTM2MTc4MzYwMzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2TjJRd1lqVXpZell0TWpBNVlTMDBNVGhqTFdFM09XUXRNMlJqWVdOaU4yUTJORFUyWDJNd1lqazJZalZrTFROaE1EQXROR1l6WVMwNVpXRXhMVFZoTVdZell6RTNZVEZoWTBCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=L3AvUi9LRGF6Y09wS1V0Y2JnY1FmbmtxVVJPSllRcXhZYTgzM1RMTHZMYz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-kbhargav%40microsoft.com)

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #4293. Fixes #4296.

### Fixed

-  Fixes [#4293](https://github.com/microsoft/BotFramework-WebChat/issues/4293) and [#4296](https://github.com/microsoft/BotFramework-WebChat/issues/4296). Fixed accessibility issues for suggested actions, by [@compulim](https://github.com/compulim), in PR [#4314](https://github.com/microsoft/BotFramework-WebChat/pull/4314)
   -  Centralized live region of suggested actions into chat history live region for better live region control
   -  Suggested actions container is now a `role="toolbar"` and uses roving tab index for multiple suggested action

## Description

We have multiple live regions in Web Chat. Since browser isn't great at handling multiple of them with simultaneously updates. To workaround browser issues, we need to consolidate all live regions.

Suggested actions container is an element with `aria-live="polite"` and `role="status"`. Both defines the liveliness for this container. We are removing both tags. Then, use the chat history live region twin to narrate the suggested actions.

As suggested actions container is no longer a live region, it can be unmounted when there are no suggested actions. Thus, we no longer need to narrate "Suggested actions container: Is empty."

### Consolidating live regions

For #4296, the issue is likely because both chat history live region and suggested actions live region are being updated at the same time. If they are updated at a slightly different time, browser may interrupt the earlier update and favor the latter update. This means either one of the live regions could skipped by the screen reader.

We are removing live region (`aria-live="polite"` and `role="status"`) from suggested actions. Instead, using the chat history live region twin to read the suggested actions (through the `<LiveRegionSuggestedActions>`).

This will likely reduce browser issues around "suggested actions are not narrated" as no more than one live region will be updated at the same time.

### Removing "is empty" narration from the suggested action container

As the suggested actions container is no longer a live region, it does not need to persist on the screen (the basic requirement of live region is the container must always appear in the DOM tree). Thus, it should not narrate "Suggested actions container: Is empty".

### Updating role of suggested actions

Also, as suggested actions are all buttons next to each other. The `role="toolbar"` is a better fit for this type of UI. To fulfill the accessibility requirement of `role="toolbar"`, we are implementing roving tab index and end-users will navigate across suggested action buttons using navigational keys (<kbd>left</kbd>/<kbd>right</kbd> for carousel/flow layout, <kbd>up</kbd>/<kbd>down</kbd> for stacked layout).

Since we are using roving tab index for the suggested actions, we will have 2 layers of focus: focus on the container and focus on each individual button. We added style options to show both focii (solid/wide for container, dashed/thin for button), similar to chat history.

### `<RovingTabIndexProvider>`

This provider will provide roving tab index functionality to all components.

We tried 2 ways to implement this component:
1. React props
   1. `useTabIndex(index: number): [number]` to return a `tabindex` value of either `0` or `-1`
   1. `useFocusHandler(index: number): () => void` and `useBlurHandler(index: number): () => void` to return an event listener that should hook to the element
1. DOM-based
   1. `useItemRef(ref: RefObject<HTMLElement>, index: number)` to automatically attach `focus`/`blur` handler and patch `tabindex` attribute via DOM

We opted for the latter approach as it deemed more lightweight on the API side, despite, it is hacking React-controlled component via `setAttribute()`. We think this is reasonable balance.

## Specific Changes

- Added 3 style options for styling the visual keyboard indicator for suggested actions
   - `suggestedActionsVisualKeyboardIndicatorColor`
   - `suggestedActionsVisualKeyboardIndicatorStyle`
   - `suggestedActionsVisualKeyboardIndicatorWidth`
- Fixed typing issues in `useDateFormatter.ts`
- Restructure live region activity into its own folder
   - `<LiveRegionActivity>` (entrypoint), `<LiveRegionAttachments>` and `<LiveRegionSuggestedActions>`
   - Renamed `<ScreenReaderActivity>` to `<LiveRegionActivity>`, this component is used by live region twin only
- New `<RovingTabIndexProvider>` and `useItemRef()` hook to bring the roving tab index functionality to all components
- Chat history live region will narrate non-presentational message activities, regardless they are rendered in the visible chat history or not
   - This will help narrating suggested actions from a message activity without `text` field (which will not be rendered in the visible chat history)
- Added new visual keyboard focus indicator for suggested actions container
   - This is required as suggested action buttons are now using roving tab index
- Added `useFocusWithin` for polyfilling browsers that does not support `:focus-within` pseudo class
- Added footnote when a message with suggested actions arrive, this is similar to footnote for messages with interactive elements or links
   - Screen reader should read "Suggested action container: Has content. Press CTRL + SHIFT + A to select."
   - This narrative should be updated in the future for clarity
- Updated port numbers for development server
   - Default server is now explicitly hosting on port 5000, as [`serve`](https://npmjs.com/package/serve) updated its default to 3000 instead
   - Embed server is now hosting on port 5002

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] I have updated documentation

## Review Checklist

> This section is for contributors to review your work.

-  [x] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] Browser and platform compatibilities reviewed
-  [x] CSS styles reviewed (minimal rules, no `z-index`)
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: __tests__/adaptiveCards.js [hunk 1]
```diff
@@ -183,8 +183,12 @@ test('unknown card', async () => {
 
   const browserConsoleErrors = await driver.manage().logs().get(logging.Type.BROWSER);
 
-  expect(browserConsoleErrors[0].level.name_).toEqual('WARNING');
-  expect(browserConsoleErrors[0].message).toContain('No renderer for attachment for screen reader of type');
+  expect(
```
Comment (compulim) [inline __tests__/adaptiveCards.js:186]: There is another legit error message in the log.

File: __tests__/basic.js [hunk 2]
```diff
@@ -136,6 +136,7 @@ test('thumbnail card with a long title and richCardWrapTitle set to default valu
 test('absolute timestamp', async () => {
   const activities = [
     {
+      channelData: {},
```
Comment (compulim) [inline __tests__/basic.js:139]: As this data structure is dumped into Redux store in Web Chat, it bypassed our patch code.

Our patch code normalizes the activity from DLJS, say:
- It must have `attachments` array, but the array can be empty
- It must have `channelData`, but it can be empty

So, if we dump it into Redux store, the data needs to be clean. In this case, `channelData` need to be `{}`.

File: packages/api/src/defaultStyleOptions.ts [hunk 3]
```diff
@@ -180,7 +180,7 @@ const DEFAULT_OPTIONS: Required<StyleOptions> = {
 
   suggestedActionKeyboardFocusIndicatorBorderColor: '#605E5C',
   suggestedActionKeyboardFocusIndicatorBorderRadius: 0,
-  suggestedActionKeyboardFocusIndicatorBorderStyle: 'solid',
+  suggestedActionKeyboardFocusIndicatorBorderStyle: 'dashed',
```
Comment (tdurnford) [inline packages/api/src/defaultStyleOptions.ts:183]: Is this a breaking change?

File: packages/component/src/LiveRegion/private/LiveRegionAttachments.tsx [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+};
+
+const LiveRegionAttachments: VFC<LiveRegionAttachmentsProps> = ({ activity }) => {
+  const { attachments = [] } = activity;
+  const createAttachmentForScreenReaderRenderer = useCreateAttachmentForScreenReaderRenderer();
+  const localizeWithPlural = useLocalizer({ plural: true });
+
+  const attachmentForScreenReaderRenderers = attachments
+    .map(attachment => createAttachmentForScreenReaderRenderer({ activity, attachment }))
+    .filter(render => render);
```
Comment (tdurnford) [inline packages/component/src/LiveRegion/private/LiveRegionAttachments.tsx:29]: nit:
```suggestion
    .filter(Boolean);
```

File: packages/component/src/hooks/internal/useFocusWithin.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
+import { useCallback, useEffect, useState } from 'react';
+
+import type { RefObject } from 'react';
+
+export default function useFocusWithin(targetRef: RefObject<HTMLElement>): readonly [boolean] {
+  const [focusWithin, setFocusWithin] = useState(false);
```
Comment (tdurnford) [inline packages/component/src/hooks/internal/useFocusWithin.ts:6]: It's not perfect for this scenario, but you should consider adding a `useBoolean` hook to Web Chat. I find it super convenient in PVA.

**Review by tdurnford — DISMISSED** [review]

File: packages/api/src/defaultStyleOptions.ts (hunk 3 above)
Comment (compulim) [reply packages/api/src/defaultStyleOptions.ts:183]: Yes, inevitable due to how focus changed. I will log it in `CHANGELOG.md`.

File: packages/component/src/hooks/internal/useFocusWithin.ts (hunk 5 above)
Comment (compulim) [reply packages/component/src/hooks/internal/useFocusWithin.ts:6]: Will file a feature request and we change many of them at once. And I will tag you as a reviewer. 🤣

**Review by tdurnford — APPROVED** [review]

**Review by tdurnford — APPROVED** [review]

File: packages/component/src/LiveRegion/private/LiveRegionAttachments.tsx (hunk 4 above)
Comment (compulim) [reply packages/component/src/LiveRegion/private/LiveRegionAttachments.tsx]: Done.
