### PR TITLE
Feedback buttons should not squash other buttons

### LINKED ISSUE #5479: Feedback form buttons should not squash other buttons
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Development build

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Others or unrelated

### Which area does this issue affect?

Chat history

### Which theme pack does this issue affect?

I did not test it on other theme packs

### What is the public URL for the website?

_No response_

### Please describe the bug

The feedback form buttons is set to `width: 100%` and it could squash other buttons, such as copy button.

### Do you see any errors in console log?

```js

```

### How to reproduce the issue?

Send this payload.

```js
{
  channelData: {
    feedbackLoop: {
      type: 'default'
    }
  },
  entities: [
    {
      '@context': 'https://schema.org',
      '@id': '',
      '@type': 'Message',
      type: 'https://schema.org/Message',
      keywords: ['AllowCopy'],
      potentialAction: [
        {
          '@type': 'LikeAction',
          actionStatus: 'PotentialActionStatus',
          target: {
            '@type': 'EntryPoint',
            urlTemplate: 'ms-directline://postback?interaction=like'
          }
        },
        {
          '@type': 'DislikeAction',
          actionStatus: 'PotentialActionStatus',
          result: {
            '@type': 'Review',
            reviewBody: "I don't like it.",
            'reviewBody-input': {
              '@type': 'PropertyValueSpecification',
              valueMinLength: 3,
              valueName: 'reason'
            }
          },
          target: {
            '@type': 'EntryPoint',
            urlTemplate: 'ms-directline://postback?interaction=dislike{&reason}'
          }
        }
      ]
    }
  ],
  text: `Occaecat cillum amet ipsum amet pariatur proident commodo eiusmod cupidatat voluptate.`,
  type: 'message'
}
```

### What do you expect?

The copy button should not look squashed.

### What actually happened?

The copy button is squashed.

### Do you have any screenshots or recordings to repro the issue?

Image

### Adaptive Card JSON

```json

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #5479.

### Fixed

- Fixed [#5479](https://github.com/microsoft/BotFramework-WebChat/issues/5479). Fixed feedback form buttons should not squash other buttons, in PR [#5480](https://github.com/microsoft/BotFramework-WebChat/pull/5480), by [@compulim](https://github.com/compulim)
   - Migrated to radio button for like/dislike where form submission is required

### UI issue

When the feedback form is enabled, the feedback buttons are grouped in a flex container and its width is set to 100%, forcing other component to squash.

### Form

A `<form>` is now put around the like/dislike button and the feedback form. It will handle all kind of like/dislike and form submissions.

### Button vs. radio button

- If no feedback form, the like/dislike button is an action, thus, they are `<input type="button">` and submitted (almost) immediately
   - Press <kbd>ESC</kbd> will do nothing as the selection has already submitted
- If feedback form is available, the like/dislike is `<input type="radio">`
   - Press <kbd>ESC</kbd> will cancel the selection of like/dislike

### Moving from `channelData` to `entities`

Today, due to limitation on Copilot Studio backend, we have to use `channelData.feedbackLoop` as a temporary solution to indicate feedback that would have review feedback.

```json
{
  "channelData": {
    "feedbackLoop": {
      "disclaimer": "...", // optional
      "type": "default"
    }
  },
  "entities": [
    {
      "@id": "",
      "@type": "Message"
      "potentialAction": [
        {
          "@type": "LikeAction"
        },
        {
          "@type": "DislikeAction"
        }
      ]
    }
  ],
  "text": "...",
  "type": "message"
}
```

In this PR, we are leveraging the Schema.org standard:

```json
{
  "entities": [
    {
      "@id": "",
      "@type": "Message"
      "potentialAction": [
        {
          "@type": "LikeAction",
          "result": {
            "@type": "UserReview",
            "reviewAspect": "..." // optional
          }
        },
        {
          "@type": "DislikeAction",
          "result": {
            "@type": "UserReview",
            "reviewAspect": "..." // optional
          }
        }
      ]
    }
  ],
  "text": "...",
  "type": "message"
}
```

The `LikeAction` literally means: "the user liked this message and that action resulted in a user review." The review content (feedback text) will become `UserReview.reviewBody` in latter PR.

We will maintain the backcompat code that migrate `channelData.feedbackLoop` to `entities[@id=""].potentialAction.result` until Copilot Studio fully onboarded the standard payload.

## Specific Changes

- Updated feedback form to do the grouping differently

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] I have updated documentation

## Review Checklist

> This section is for contributors to review your work.

-  [x] ~Accessibility reviewed (tab order, content readability, alt text, color contrast)~
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] CSS styles reviewed (minimal rules, no `z-index`)
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/component/src/ActivityFeedback/ActivityFeedback.tsx [hunk 1]
```diff
@@ -1,27 +1,69 @@
...
+    [selectedActionRef]
+  );
 
-function ActivityFeedback({ activity }: ActivityFeedbackProps) {
   return (
-    <ActivityFeedbackComposer activity={activity}>
-      <InternalActivityFeedback />
-    </ActivityFeedbackComposer>
+    <form
+      className={classNames('webchat__feedback-form-real', feedbackForm + '')}
```
Comment (OEvgeny) [inline packages/component/src/ActivityFeedback/ActivityFeedback.tsx:55]: `feedback-form-real` :grin:

File: packages/component/src/ActivityFeedback/providers/private/FocusPropagation.ts [hunk 2]
```diff
@@ -0,0 +1,10 @@
+import { type OrgSchemaAction } from 'botframework-webchat-core';
+import { createPropagation } from 'use-propagate';
+
+const {
+  PropagationScope: FocusPropagationScope,
```
Comment (OEvgeny) [inline packages/component/src/ActivityFeedback/providers/private/FocusPropagation.ts:5]:
```suggestion
  PropagationScope: ActivityFeedbackFocusPropagationScope,
```

File: packages/component/src/ActivityFeedback/providers/useFeedbackText.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
+import { type Dispatch, type SetStateAction } from 'react';
+import useActivityFeedbackContext from './private/useActivityFeedbackContext';
+
+export default function useFeedbackText(): readonly [string, Dispatch<SetStateAction<string>>] {
+  return useActivityFeedbackContext().feedbackTextState;
```
Comment (OEvgeny) [inline packages/component/src/ActivityFeedback/providers/useFeedbackText.ts:5]: Again, context trapping. We need to talk more about this.

File: packages/component/src/ActivityFeedback/ActivityFeedback.tsx (hunk 1 above)
Comment (compulim) [reply packages/component/src/ActivityFeedback/ActivityFeedback.tsx:55]: I was renaming `feedback-form` to `feedback-loop` and this `feedback-form-real` is `feedback-form`. Didn't finish my work yet. 🤣

File: packages/component/src/ActivityFeedback/providers/useFeedbackText.ts (hunk 3 above)
Comment (compulim) [reply packages/component/src/ActivityFeedback/providers/useFeedbackText.ts:5]: Let's experiment something new in this PR.

**Review by OEvgeny — APPROVED** [review]

File: packages/component/src/Styles/StyleSet/ThumbButton.ts [hunk 4]
```diff
@@ -85,7 +84,7 @@ export default function () {
           color: CSSTokens.ColorSubtle
         },
 
-        '&.webchat__thumb-button--has-submitted:has(.webchat__thumb-button__input:not(:checked)) .webchat__thumb-button__tooltip':
+        '&.webchat__thumb-button--has-submitted:has(.webchat__thumb-button__input:not(:checked):not([aria-pressed="true"])) .webchat__thumb-button__tooltip':
```
Comment (OEvgeny) [inline packages/component/src/Styles/StyleSet/ThumbButton.ts:87]: These selectors are getting out of hand :rofl:

**Review by OEvgeny — APPROVED** [review]
