### PR TITLE
Insert typing activity into transcript

### LINKED ISSUE #3431: First welcome message is delayed for 5 seconds
## Version

`4.10.0`

## Describe the bug

The first welcome message coming in is being delayed for 5 seconds. Probably due to recent accessibility fix that would delay message up to 5 seconds if their "reply-to-id" activity was not arrived yet.

## Steps to reproduce

1. Go to MockBot2
1. You should see "Hello and welcome!"

## Expected behavior

Instead, the "Hello and welcome!" arrive 5 seconds after the Web Socket packet has arrived.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #3431.

### Fixed

-  Fixes [#3431](https://github.com/microsoft/BotFramework-WebChat/issues/3431). Activities should not be delayed due to missing activity of type "typing", by [@compulim](https://github.com/compulim) in PR [#3554](https://github.com/microsoft/BotFramework-WebChat/pull/3554)

## Description

Today, typing activity was not inserted into transcript. This is causing incoming activity to be delayed if they are replying to that typing activity.

Tomorrow, we are inserting the typing activity into the transcript but not displaying them. Since they are in the transcript, incoming activities will be able to infer them and not to be delayed.

## Specific Changes

- Updated `reducer/activities.js` not to filter out activity of type `typing`
- Added warning if an activity is being delayed because the activity it is replying to was not in the transcript

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [x] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/core/src/reducers/activities.js [hunk 1]
```diff
@@ -105,10 +105,7 @@ export default function activities(state = DEFAULT_STATE, { meta, payload, type
 
     case INCOMING_ACTIVITY:
       // TODO: [P4] Move "typing" into Constants.ActivityType
```
Comment (corinagum) [inline packages/core/src/reducers/activities.js:107]: File an issue and put issue number in this line of code.

**Review by corinagum — APPROVED** [review]
LGTM, pending one comment.
