### PR TITLE
Color contrast ratio fixes & downloadIcon narrator accessibility

### LINKED ISSUE #1305: [MAS1.4.3] Luminosity Contrast Ratio of 'Upload File' and 'Send' button icons is less than required.
**Actual Result:**
Luminosity Contrast Ratio of 'Upload File' button icon is 2.8:1 and 'Send' button icon is 1.7:1.

**Expected Result:**
Luminosity Contrast of 'Upload File' and 'Send' button icons should be greater than or equal to 4.5:1.

**Repro Steps:**
1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](url) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Open 'Colour Contrast Analyser' and select Foreground & Background color of mentioned elements one by one.
4. Notice value of Luminosity Contrast Ratio.
 
**User Impact:**
Users with low vision or Color blindness will find it difficult to access content with low luminosity contrast ratio.

**MAS Reference:**
[MAS 1.4.3 – Contrast (Minimum) (17)](url)

**Test Environment:**
OS: Windows 10
OS Build: 17134.345
OS Version: 1803
Browser: Edge
Tool: Colour Contrast Analyser

**Attachment:**
mas1 4 3_botframework_webchat_uploadfile_send

### PR DESCRIPTION
**Pull request by corinagum**
Fix #1305, #1316,  #1341,  #1411

### CODE REVIEW

File: packages/component/src/Attachment/DownloadAttachment.js [hunk 1]
```diff
@@ -28,7 +29,7 @@ export default connectToWebChat(
                 <div className="size">{ format(size) }</div>
             }
           </div>
-          <DownloadIcon className="icon" size={ 1.5 } />
+          <DownloadIcon className="icon" language={ language } size={ 1.5 } />
```
Comment (cwhitten) [inline packages/component/src/Attachment/DownloadAttachment.js]: instead of passing the language and letting `<DownloadIcon />` do the localization, could we just add a `label` prop and have `<DownloadAttachment />` pass in the already localized string? I like the separation there a bit better.

File: packages/component/src/Attachment/Assets/DownloadIcon.js [hunk 2]
```diff
@@ -1,7 +1,10 @@
 import React from 'react';
 
-export default ({ className, size = 1 }) =>
+import { localize } from '../../Localization/Localize';
+
+export default ({ className, language, size = 1 }) =>
   <svg
+    aria-label={ localize('Download file', language) }
```
Comment (a-b-r-o-w-n) [inline packages/component/src/Attachment/Assets/DownloadIcon.js]: Since this seems to be a presentational component, it may make more sense to do the localization up a level and just pass a `label` prop instead. That will give this component a bit more flexibility.

File: packages/component/src/Attachment/DownloadAttachment.js (hunk 1 above)
Comment (corinagum) [reply packages/component/src/Attachment/DownloadAttachment.js]: 👍

File: packages/component/src/Localization/sv-SE.js [hunk 3]
```diff
@@ -3,6 +3,7 @@ export default {
   // 'Microphone off': '',
   // 'Microphone on': '',
   'Listening…': 'Lyssnar…',
+  'Download file': '',
```
[the remark this answers is not in the document]
Comment (corinagum) [reply packages/component/src/Localization/sv-SE.js]: thanks for catching!

**Comment by corinagum** [comment]
@cwhitten ping with PR fixes :)
