### PR TITLE
Fix Adaptive Cards `TextBlock` element missing `aria-level`

### LINKED ISSUE #4327: Title in Hero Card does not have `aria-level` specified
## Screenshots

image

## Version

`main`

## Describe the bug

In Adaptive Cards library, by default, all `TextBlock` with `style="heading"` will have `role="heading"` set. However, the required attribute, `aria-level`, was not set. To set the `aria-level`, we need to *explicitly* specify `hostConfig.textBlock.headingLevel`.

Adaptive Cards library added this new host config option in their https://github.com/microsoft/AdaptiveCards/issues/5635 and https://github.com/microsoft/AdaptiveCards/pull/5698.

Without specifying this new host config option, the rendered DOM tree will be invalid by WCAG 4.1.2 (aria-required-attr). This is because all elements with `role="heading"` MUST have `aria-level` specified.

## Steps to reproduce

1. Talk to MockBot
2. Say "herocard"
3. Inspect the element "Details about image 1"

## Expected behavior

The element has `role="heading"`, however, it does not have `aria-level` attribute specified.

## Action items

Make sure to update our `validateDOMTree()` function to verify this issue on a broader scale.

## Additional context

New bug https://github.com/microsoft/AdaptiveCards/issues/7566 filed to `microsoft/AdaptiveCards` repo.

- https://github.com/microsoft/AdaptiveCards/issues/5635
- https://github.com/microsoft/AdaptiveCards/pull/5698

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #4327.

### Fixed

-  Fixes [#4327](https://github.com/microsoft/BotFramework-WebChat/issues/4327). In Adaptive Cards, `TextBlock` with `style="heading"` should have `aria-level` set, by [@compulim](https://github.com/compulim), in PR [#4329](https://github.com/microsoft/BotFramework-WebChat/issues/4329)

## Description

By default, Adaptive Cards generate DOM with `role="heading"` without `aria-level` set. This violated [WCAG 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html) ([ARIA5](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA5)).

In order to set `aria-level`, we need to explicitly set `ACHostConfig.textBlock.headingLevel` to `1`. This is an [undocumented option](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#schema-textblockconfig) introduced by https://github.com/microsoft/AdaptiveCards/issues/5635 and https://github.com/microsoft/AdaptiveCards/pull/5698.

## Design

This is code in [Adaptive Cards repo `card-elements.ts`](https://github.com/microsoft/AdaptiveCards/blob/ff28a1fd75d5dbe62d3fc3940f47652190f5a506/source/nodejs/adaptivecards/src/card-elements.ts#L920).

image

If the Adaptive Card `TextBlock` element has `style="heading"`, the `role="heading"` will be applied. However, `aria-level` is not set unless `ACHostConfig.textBlock.headingLevel` is set. This is an undocumented option and *required* for accessibility. Otherwise, we would fail with [WCAG 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html) ([ARIA5](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA5)).

We need to explicitly set `ACHostConfig.textBlock.headingLevel` to make sure `aria-level` is set on `role="heading"`. As we do not use heading, we default it to level 1.

## Specific Changes

- Update `adaptiveCardHostConfig.ts` to add `textBlock.headingLevel` to `1`
- Update `verifyDOMIntegrity.js` for verifying our DOM tree is good
- Add `verifyDOMIntegrity()` call to all card-related attachments

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] I have updated documentation

## Review Checklist

> This section is for contributors to review your work.

-  [x] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js [hunk 1]
```diff
@@ -3,16 +3,22 @@
...
-
-      console.warn(message, element);
-
-      throw new Error(message);
-    }
+    element
+      .getAttribute('aria-labelledby')
+      .split(' ')
+      .map(labelId => labelId.trim())
+      .filter(Boolean)
```
Comment (tdurnford) [inline packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js:10]: :)

File: packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js [hunk 2]
```diff
@@ -41,4 +47,17 @@ export default function verifyDOMIntegrity() {
       throw new Error(message);
     }
   });
+
+  // Elements of `role="heading"` must have `aria-level` set
+  [].forEach.call(document.querySelectorAll('[role="heading"]'), element => {
+    const ariaLevel = +element.getAttribute('aria-level');
+
+    if (!(ariaLevel >= 1 && ariaLevel === ~~ariaLevel)) {
```
Comment (tdurnford) [inline packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js:55]: Interesting... when would `ariaLevel === ~~ariaLevel` be `false`? ... `ariaLevel = true` is the only scenario I can think of for `!(ariaLevel >= 1 && ariaLevel === ~~ariaLevel)` to be `true`.

`!(true >= 1 && true === ~~true) => true`

**Review by tdurnford — APPROVED** [review]

File: packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js (hunk 2 above)
Comment (compulim) [reply packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js:55]: Hehe, `0.1`.

```
> value = 0.1
0.1
> value === ~~value
false
```

Comment (compulim) [reply packages/test/page-object/src/globals/pageObjects/verifyDOMIntegrity.js:55]: A very large integer number could also return `false` for `bigInteger === ~~bigInteger`... such as an Unix epoch.
