### PR TITLE
Fix undefined notification should not break

### LINKED ISSUE #3383: Passing `undefined` to `message` of notification toast will throw exception
## Version

`4.9.2` or `master`

## Describe the bug

Passing `undefined` to `message` of notification toast will throw exception.

## Steps to reproduce

1. Call `SET_NOTIFICATION` or `useSetNotification` hook, with a structure of `{}`

## Expected behavior

Web Chat should show an empty toast, or a red box.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #3383.

### Fixed

-  Fixes [#3383](https://github.com/microsoft/BotFramework-WebChat/issues/3383). Fixed notification toast should not break when most fields are `undefined`, by [@compulim](https://github.com/compulim) in PR [#3384](https://github.com/microsoft/BotFramework-WebChat/issues/3384)

## Description

When a notification is passed with most fields `undefined`, it should not break.

## Specific Changes

- Defaulting some critically required fields (`id` and `level`).
- When `message` is undefined, assume it is empty string

---

-  [x] Testing Added

### CODE REVIEW

File: packages/core/src/actions/setNotification.js [hunk 1]
```diff
@@ -1,6 +1,18 @@
+import uniqueID from '../utils/uniqueID';
+
 const SET_NOTIFICATION = 'WEB_CHAT/SET_NOTIFICATION';
 
 export default function setNotification({ alt, data, id, level, message }) {
+  if (!id || typeof id !== 'string') {
+    console.warn('botframework-webchat: The "id" argument passed to "setNotification" must be a string, defaulting to a random value.');
```
Comment (corinagum) [inline packages/core/src/actions/setNotification.js:7]:
```suggestion
    console.warn('botframework-webchat: The "id" argument passed to "setNotification" must be a string; defaulting to a random value.');
```

File: packages/core/src/actions/setNotification.js [hunk 2]
```diff
@@ -1,6 +1,18 @@
...
+    id = uniqueID();
+  }
+
+  if (!level || typeof level !== 'string') {
+    console.warn('botframework-webchat: The "level" argument passed to "setNotification" must be a string, defaulting to "info".');
```
Comment (corinagum) [inline packages/core/src/actions/setNotification.js:12]:
```suggestion
    console.warn('botframework-webchat: The "level" argument passed to "setNotification" must be a string; defaulting to "info".');
```
