### PR TITLE
Accessibility on focus management and disable Adaptive Cards

### LINKED ISSUE #1427: Sample: Disable Adaptive Cards after submit/obsoleted
## Goals

- Write a new attachment renderer that will disable Adaptive Card interactivity if a certain condition is met
   - If the Adaptive Card is no longer the last visible activity sent from the bot, or there is a message sent by the user succeeding it, disable interactivity on the Adaptive Card
- There could be more than one Adaptive Card form available on the page
- Also consider, if "expand card" action button should be disabled or not. It was because "expand card" button should not be counted as "form submission", we might not want to disable expand/collapse feature
   - If implementer is not familiar with this feature, should consult the "Adaptive Card visualizer" page for details

## Non-goals

It should not use jQuery or any other DOM-manipulating libraries to achieve the goal. It must use pure React.

## Reference

We have a sample named "presentation mode". It showed the ability to disable interactivity of the whole Web Chat UI, including Adaptive Card content. The implementer can look into that to understand how to disable interactivity for just a specific attachment

### LINKED ISSUE #2669: [Accessibility][Screen Readers][bot name - Test in Web Chat]: Screen reader is not providing the descriptive information when focus is on "New Messages" button.
Original: https://github.com/microsoft/BotFramework-Emulator/issues/1978

**User Impact:**
Users who depends on screen reader will get confuse if screen reader is not providing the descriptive information when focus is on "New Messages" button.

**Test Environment:**
OS: Version: 1903(OS Build 18956.1000) 
URL: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/8d5ceb22-44c7-4367-bfc6-07378096e055/resourceGroups/sddsddd/providers/Microsoft.BotService/botServices/avinash/channels
Browser: Edge
Screen Reader: Narrator

**Pre requisite:**
create new web app bot.

**Repro Steps:**
1. Turn on Narrator.
2. Open https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/8d5ceb22-44c7-4367-bfc6-07378096e055/resourceGroups/sddsddd/providers/Microsoft.BotService/botServices/avinash/channels in Edge.
3. Navigate to already created web app bot.
4. Navigate to "Test in Web Chat" element and activate it.
5. Now "Test" screen will be displayed.
6. Navigate to "New Messages" button and verify whether screen reader is providing the descriptive information when focus is on "New Messages" button.

**Actual Result:**
Screen reader is not providing the descriptive information when focus is on "New Messages" button.
Screen reader is reading as "New Messages button"

**Expected Result:**
Screen reader should provide the descriptive information ,when focus is on "New Messages" button.
Screen reader should read as "New Messages button, hit ENTER to see the new messages".

**Note:**
Same issue repro with NVDA also.

**MAS Reference**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D&cid=ea080456-8c71-4c66-b1f0-9a2a20e08097](url)

**Attachment:**
[New Messages button descriptive.zip](https://github.com/microsoft/BotFramework-WebChat/files/3925543/New.Messages.button.descriptive.zip)

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #1427. Fixes #2669.

### Added

-  Fixes [#1427](https://github.com/microsoft/BotFramework-WebChat/issues/1427). Support `disabled` prop and added `actionPerformedClassName` in Adaptive Card and other legacy cards, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/issue/3150)

### Fixed

-  Fixes [#2669](https://github.com/microsoft/BotFramework-WebChat/issues/2669). The "New messages" button will be accessible through <kbd>TAB</kbd> key, inbetween the last read and last unread activities, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/issues/3150).

### Changed

-  Bumped all dependencies to latest versions, by [@compulim](https://github.com/compulim) in PR [#2985](https://github.com/microsoft/BotFramework-WebChat/pull/2985), [#3012](https://github.com/microsoft/BotFramework-WebChat/pull/3012) and [#3150](https://github.com/microsoft/BotFramework-WebChat/pull/3150)
   -  Production dependencies
      -  `component`
         -  [`react-film@2.1.0`](https://npmjs.com/package/react-film)
         -  [`react-scroll-to-bottom@2.0.0`](https://npmjs.com/package/react-scroll-to-bottom)

### Samples

-  Resolves [#1427](https://github.com/microsoft/BotFramework-WebChat/issues/1427), added disable cards after submission sample, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/issue/3150)

## Description

This will provide a better accessibility and UX for answering prompts via Adaptive Card and other cards.

Fixed accessibility around focus management on the "New messages" button and how UIs are disabled.

## Specific Changes

> Note: in the screen recordings, the dotted line for focus is only shown for illustrative purpose only. It is not going into production code.

### Accessibility for disabled elements

Disabled elements will have the focus retained on them temporarily. When the user focus to another element, the disabled element will have `disabled` attribute set, thus they will not be able to <kbd>TAB</kbd> back once <kbd>TAB</kbd> out.

recording (19)

#### Excerpt from code comment

Differences between `<button>` and `<AccessibleButton>`:
- Disable behavior
   - When the widget is disabled
      - Set `aria-disabled` attribute to `true`
      - Set `readonly` attribute
      - If the focus is on, don't set `disabled` attribute, until it is blurred
         - Otherwise, set `disabled` attribute
      - Remove `onClick` handler
   - Why we need this
      - Browser compatibility: when the widget is disabled, different browser send focus to different places
      - When the widget become disabled, it's reasonable to keep the focus on the same widget for an extended period of time
         - When the user press <kbd>TAB</kbd> after the current widget is disabled, it should jump to the next non-disabled widget

Developers using this accessible widget will need to:
- Style the disabled widget themselves, using CSS query `:disabled, [aria-disabled="true"] {}`
- Modify all code that check disabled through `disabled` attribute to use `aria-disabled="true"` instead
   - `aria-disabled="true"` is the source of truth
- If the widget is contained by a `<form>`, the developer need to filter out some `onSubmit` event caused by this widget

### Correct tab order for "New messages" button

"New messages" button is appended after the last read activity, but not last shown activity. I.e. this make the button <kbd>TAB</kbd>-able.

recording (20)

## Additional context

- [`react-film@2.0.2` -> `@2.1.0`](https://github.com/spyip/react-film/compare/v2.0.2...v2.1.0)
- [`react-scroll-to-bottom@1.3.2` -> `@2.0.0`](https://github.com/compulim/react-scroll-to-bottom/compare/v1.3.2...v2.0.0)

---

-  [x] Testing Added

### CODE REVIEW

File: packages/component/src/SendBox/SuggestedActions.js [hunk 1]
```diff
@@ -98,6 +98,7 @@ const SuggestedActions = ({ className, suggestedActions = [] }) => {
         dir={direction}
         flipperBlurFocusOnClick={true}
         showDots={false}
+        showScrollBar={false}
```
Comment (compulim) [inline packages/component/src/SendBox/SuggestedActions.js:101]: Today, we show a white semi-transparent scroll bar. It think we should hide it.

image

File: packages/component/src/Styles/StyleSet/ScrollToEndButton.js [hunk 2]
```diff
@@ -22,6 +22,7 @@ export default function createScrollToEndButtonStyle({
     outline: 0,
     padding: paddingRegular,
     position: 'absolute',
+    zIndex: 1, // We formed a stacking context in the parent container, so we can use "z-index" here.
```
Comment (compulim) [inline packages/component/src/Styles/StyleSet/ScrollToEndButton.js:25]: Unfortunately, we need to use `zIndex` to make the "New messages" button pop on top of all bubbles. This is because we re-ordered the DOM to put the "New messages" button between bubbles, instead of appending after all bubbles. We need the re-order to maintain tab order.

File: packages/testharness/src/index.js [hunk 3]
```diff
@@ -1,6 +1,14 @@
+import 'script-loader!../node_modules/@babel/standalone/babel.min.js';
```
Comment (compulim) [inline packages/testharness/src/index.js:1]: I know it's ugly, but it reduce boilerplate code and this is for test harness only.

File: samples/05.custom-components/l.disable-adaptive-cards/index.html [hunk 4]
```diff
@@ -0,0 +1,217 @@
+<!DOCTYPE html>
```
Comment (compulim) [inline samples/05.custom-components/l.disable-adaptive-cards/index.html:1]: Will do some clean up on this soon.

File: CHANGELOG.md [hunk 5]
```diff
@@ -50,10 +51,13 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
    -  Skip stripping Markdown for non-Markdown text content.
 -  Fixes [#3155](https://github.com/microsoft/BotFramework-WebChat/issues/3155). Patch incoming activities with null fields, by [@compulim](https://github.com/compulim) in PR [#3154](https://github.com/microsoft/BotFramework-WebChat/pull/3154)
+-  Fixes [#2669](https://github.com/microsoft/BotFramework-WebChat/issues/2669) and [[#3136](https://github.com/microsoft/BotFramework-WebChat/issues/3136). The "New messages" button will be accessible through <kbd>TAB</kbd> key, inbetween the last read and first unread activity, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/issues/3150).
+   -  After the "New message" button is clicked, focus will be moved to the first interactive UI of unread activity or the send box.
+-  Fixes [#3135](https://github.com/microsoft/BotFramework-WebChat/issues/3135). If the current widget is disabled, the focus will be stayed until the next <kbd>TAB</kbd> key, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/pull/3150)
```
Comment (tdurnford) [inline CHANGELOG.md:56]:
```suggestion
-  Fixes [#3135](https://github.com/microsoft/BotFramework-WebChat/issues/3135). If the current widget is disabled, it will keep focus until the next <kbd>TAB</kbd> key is pressed, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/pull/3150)
```

File: CHANGELOG.md [hunk 6]
```diff
@@ -50,10 +51,13 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
 
 ### Changed
 
--  Bumped all dependencies to latest versions, by [@compulim](https://github.com/compulim) in PR [#2985](https://github.com/microsoft/BotFramework-WebChat/pull/2985) and [#3012](https://github.com/microsoft/BotFramework-WebChat/pull/3012)
+-  Bumped all dependencies to latest versions, by [@compulim](https://github.com/compulim) in PR [#2985](https://github.com/microsoft/BotFramework-WebChat/pull/2985), [#3012](https://github.com/microsoft/BotFramework-WebChat/pull/3012) and [#3150](https://github.com/microsoft/BotFramework-WebChat/pull/3150)
```
Comment (tdurnford) [inline CHANGELOG.md:60]:
```suggestion
-  Bumped all dependencies to the latest versions, by [@compulim](https://github.com/compulim) in PR [#2985](https://github.com/microsoft/BotFramework-WebChat/pull/2985), [#3012](https://github.com/microsoft/BotFramework-WebChat/pull/3012) and [#3150](https://github.com/microsoft/BotFramework-WebChat/pull/3150)
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -112,10 +118,11 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
 
-## Samples
+### Samples
 
 -  Resolves [#2806](https://github.com/microsoft/BotFramework-WebChat/issues/2806), added [Single sign-on with On Behalf Of Token Authentication](https://webchat-sample-obo.azurewebsites.net/) sample, by [@tdurnford](https://github.com/tdurnford) in [#2865](https://github.com/microsoft/BotFramework-WebChat/pull/2865)
 -  Resolves [#2481](https://github.com/microsoft/BotFramework-WebChat/issues/2481), added selectable audio input device sample, by [@compulim](https://github.com/compulim) in PR [#3079](https://github.com/microsoft/BotFramework-WebChat/pull/3079)
+-  Resolves [#1427](https://github.com/microsoft/BotFramework-WebChat/issues/1427), added disable cards after submission sample, by [@compulim](https://github.com/compulim) in PR [#3150](https://github.com/microsoft/BotFramework-WebChat/issue/3150)
```
Comment (tdurnford) [inline CHANGELOG.md:125]: Is this PR adding the samples?

File: docs/ACCESSIBILITY.md [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+## Definitions
+
+### Focusable
+
+-  Interactive UI element that can be focused programmatically or via user gesture other than the <kbd>TAB</kbd> key, e.g. tap or mouse click
+-  It is optional to allow <kbd>TAB</kbd> key to focus on this element
+
+### Tabbable
+
+-  A [focusable](#focusable) which can be focused on by pressing <kbd>TAB</kbd> key
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:37]:
```suggestion
-  A [focusable](#focusable) element which can be focused on by pressing <kbd>TAB</kbd> key
```

File: docs/ACCESSIBILITY.md [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+
+## UX: A series of decisions
+
+> This is related to https://github.com/microsoft/BotFramework-WebChat/issues/3135.
+
+### User story
+
+The bot send a question with a set of predefined answers as UI buttons that will drive the conversation towards a particular goal (a.k.a. decision buttons).
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:45]:
```suggestion
The bot sends a question with a set of predefined answers as UI buttons that will drive the conversation towards a particular goal (a.k.a. decision buttons).
```

File: docs/ACCESSIBILITY.md [hunk 10]
```diff
@@ -0,0 +1,139 @@
...
+
+After the user make the decision by clicking on a button, the decision is being submitted. The user is not allowed to reselect another decision.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:47]:
```suggestion
After the user makes their decision by clicking on a button, the decision is submitted. The user is not allowed to reselect another decision.
```

File: docs/ACCESSIBILITY.md [hunk 11]
```diff
@@ -0,0 +1,139 @@
...
+
+The bot will then send another question with another set of answers.
+
+### Positive user experience
+
+We should disable buttons that are not part of the decision. Momentarily, the next set of answers will arrive. Since we must not change focus asynchronously outside of user gesture, the user is required to press <kbd>TAB</kbd> to get into the next set of decision buttons.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:53]: The english on this was a little rough. Cleaned it up the best I could. Might want to make sure it still conveys everything correctly.

```suggestion
Once the user makes their selection, we should disable the decision buttons. Since the next question and set of possible decisions do not arrive immediately from the bot, we  can not change the focus asynchronously outside of user gestures. Consequently, the user is required to press <kbd>TAB</kbd> to move the focus to the next set of decision buttons.
```

File: docs/ACCESSIBILITY.md [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+
+When the user <kbd>TAB</kbd> out of the current button and into the next set of buttons, we should disable all previous decision buttons including the one the user chose. This will give a more consistent UX on how buttons are disabled.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:55]:
```suggestion
When the user presses the <kbd>TAB</kbd> key to move the focus from the current button to the next set of buttons, all the previous decision buttons should be disabled including the button the user chose. This will give a more consistent UX on how buttons are disabled.
```

File: docs/ACCESSIBILITY.md [hunk 13]
```diff
@@ -0,0 +1,139 @@
...
+
+Since disabling buttons will also hide them from screen reader, we should add a screen reader-only text to tell the user which answer they chose.
+
+### Exceptions
+
+-  If no tabbable UI after the current disabled button, the next <kbd>TAB</kbd> should goes into the send box.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:61]:
```suggestion
-  If there is not a tabbable UI after the current disabled button, the next <kbd>TAB</kbd> should move the focus to the send box.
```

File: docs/ACCESSIBILITY.md [hunk 14]
```diff
@@ -0,0 +1,139 @@
...
+
+### Implementation
+
+When an UI is being disabled:
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:65]: "In English, we use articles on the basis of the vowel sound and not only the letter." Haha english is the worst. 

```suggestion
When a UI element is being disabled:
```

File: docs/ACCESSIBILITY.md [hunk 15]
```diff
@@ -0,0 +1,139 @@
...
+
+-  All UI will be manually styled, based on `:disabled, [aria-disabled="true"]` query
+   -  User agent stylesheet do not take account into `aria-disabled` attribute
+-  Set `aria-disabled` attribute to `true`
+   -  If it is a `<button>`, set `onClick` to a handler that call `event.preventDefault()`
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:70]:
```suggestion
   -  If the element is a `<button>`, `onClick` is set to a handler that calls `event.preventDefault()`
```

File: docs/ACCESSIBILITY.md [hunk 16]
```diff
@@ -0,0 +1,139 @@
...
+   -  If it is a `<input type="text">` or `<textarea>`, set `readOnly` to `true`
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:71]:
```suggestion
   -  If the element is an `<input type="text">` or `<textarea>`, `readOnly` is set to `true`
```

File: docs/ACCESSIBILITY.md [hunk 17]
```diff
@@ -0,0 +1,139 @@
...
+-  If it is currently focused, wait until `onBlur` event and set `disabled` attribute
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:72]:
```suggestion
-  If the element is currently focused, the component will wait until the `onBlur` event is called to set the `disabled` attribute to `true`
```

File: docs/ACCESSIBILITY.md [hunk 18]
```diff
@@ -0,0 +1,139 @@
...
+   -  Otherwise, set `disabled` attribute immediately
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:73]:
```suggestion
   -  Otherwise, the `disabled` attribute will be set to `true` immediately
```

File: docs/ACCESSIBILITY.md [hunk 19]
```diff
@@ -0,0 +1,139 @@
...
+
+> List of elements support `disabled` attribute can be found in [this article](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).
+
+### Additional context
+
+By default, HTML is static. Thus, the default `disabled` implementation works on a static web page.
+
+On a dynamic web page, when `disabled` is being applied to a focusing element (`document.activeElement`), the focus change varies between browsers:
+
+-  Chrome will keep the focus on current element invisible to JavaScript or CSS
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:83]:
```suggestion
-  Chrome will keep the focus on the current element invisible to JavaScript or CSS
```

File: docs/ACCESSIBILITY.md [hunk 20]
```diff
@@ -0,0 +1,139 @@
...
+   -  On <kbd>TAB</kbd>, it jump to next tabbable sibling or descendants of them (depth-first search)
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:84]: If it's a depth-first search, maybe reorder "sibling or descendants" to "descendant or sibling"

```suggestion
   -  On <kbd>TAB</kbd>, focus will move to next tabbable sibling or descendant (depth-first search)
```

File: docs/ACCESSIBILITY.md [hunk 21]
```diff
@@ -0,0 +1,139 @@
...
+-  Firefox will send the focus to the parent, invisibly
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:85]: invisibly?

File: docs/ACCESSIBILITY.md [hunk 22]
```diff
@@ -0,0 +1,139 @@
...
+   -  On <kbd>TAB</kbd>, it jump to the first tabbable sibling or descendants of them (depth-first search)
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:86]:
```suggestion
   -  On <kbd>TAB</kbd>, focus will move to the first tabbable descendant or sibling (depth-first search)
```

File: docs/ACCESSIBILITY.md [hunk 23]
```diff
@@ -0,0 +1,139 @@
...
+-  Edge UWP and IE11 will send the focus to `<body>`, invisibly
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:87]: Again, not sure what you mean by 'invisibly.' Is it invisible to js and css like with Chrome?

File: docs/ACCESSIBILITY.md [hunk 24]
```diff
@@ -0,0 +1,139 @@
...
+   -  On <kbd>TAB</kbd>, it jump to the first tabbable on the web page
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:88]:
```suggestion
   -  On <kbd>TAB</kbd>, focus moves to the first tabbable element on the web page
```

File: docs/ACCESSIBILITY.md [hunk 25]
```diff
@@ -0,0 +1,139 @@
...
+
+## UX: New messages button
+
+> This is related to [#3136](https://github.com/microsoft/BotFramework-WebChat/issues/3136).
+
+### User story
+
+While the user scrolled up to view past conversation, the bot send a message with few decision buttons to the user. To make the user aware of the arriving message, a "New messages" button is shown on the screen.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:96]:
```suggestion
When the user scrolls up to view past conversation and the bot sends a message with new decision buttons to the user, Web Chat places a "New messages" button on the screen to make the user aware of the new message.
```

File: docs/ACCESSIBILITY.md [hunk 26]
```diff
@@ -0,0 +1,139 @@
...
+
+The user should be able to <kbd>TAB</kbd> into the "New messages" button. Clicking on it will scroll the view to the first decision button and put the focus on it.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:98]:
```suggestion
The user should be able to move the focus to the "New messages" button by pressing <kbd>TAB</kbd>. Clicking on it will scroll the view to the first decision button and put the focus on it.
```

File: docs/ACCESSIBILITY.md [hunk 27]
```diff
@@ -0,0 +1,139 @@
...
+
+### Exceptions
+
+If the new message do not contains any tabbable UI, it should focus to the send box after clicking on the "New messages" button.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:102]:
```suggestion
If the new message does not contain any tabbable UI, it should move the focus to the send box after clicking on the "New messages" button.
```

File: docs/ACCESSIBILITY.md [hunk 28]
```diff
@@ -0,0 +1,139 @@
...
+
+### Implementation
+
+The "New messages" button should be positioned in the DOM between the last read message, and the first unread message.
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:106]:
```suggestion
The "New messages" button should be positioned in the DOM between the last read message and the first unread message.
```

File: docs/ACCESSIBILITY.md [hunk 29]
```diff
@@ -0,0 +1,139 @@
...
+
+-  Find the first message with a tabbable UI self or descendant
+-  If a [tabbable](#tabbable) UI is found, focus on it
+   -  Otherwise, focus on the send box wihout soft keyboard
+
+## Do and don't
+
+### Do
+
+-  After an element is removed from tab order, do put the focus on next logical tabbable
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:118]:
```suggestion
-  After an element is removed from tab order, put the focus on next logical tabbable element
```

File: docs/ACCESSIBILITY.md [hunk 30]
```diff
@@ -0,0 +1,139 @@
...
+   -  "New messages" button
+      -  After clicking on the "New messages" button, put the focus on the first tabbable of all unread activities, or the send box as last resort
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:120]:
```suggestion
      -  After clicking on the "New messages" button, the focus should move to the first tabbable element of all the unread activities or the send box as last resort
```

File: docs/ACCESSIBILITY.md [hunk 31]
```diff
@@ -0,0 +1,139 @@
...
+      -  Related to [#3136](https://github.com/microsoft/BotFramework-WebChat/issues/3136)
+   -  Suggested actions buttons
+      -  After clicking on any suggested action buttons, put the focus on the send box, without soft keyboard
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:123]: I'm assuming soft keyboards are on mobile?

```suggestion
      -  After clicking on any suggested action buttons, the focus should move to the send box without soft keyboard
```

File: docs/ACCESSIBILITY.md [hunk 32]
```diff
@@ -0,0 +1,139 @@
...
+      -  For better UX, the activity asking the question should have the answer inlined
+      -  Related to [#XXX](https://github.com/microsoft/BotFramework-WebChat/issues/XXX)
+
+### Don't
+
+-  Don't use numbers other than `0` or `-1` in `tabindex` attribute
+   -  This will pollute the hosting environment
+-  In an activity with question and answers, after clicking on a decision button, don't disable the button
+   -  When the user read the activity, the screen reader will only read the question but not the chosen answer
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:132]:
```suggestion
   -  When the user reads the activity, the screen reader will only read the question but not the chosen answer
```

File: docs/ACCESSIBILITY.md [hunk 33]
```diff
@@ -0,0 +1,139 @@
...
+   -  It is okay to disable buttons that were not chosen as answer
+   -  It is okay to disable all buttons, as long as the answer will be read by the screen reader
+   -  Related to [#3135](https://github.com/microsoft/BotFramework-WebChat/issues/3135)
+-  Don't move focus when an activity arrive (or asynchronously)
```
Comment (tdurnford) [inline docs/ACCESSIBILITY.md:136]:
```suggestion
-  Don't move focus when an activity arrives (or asynchronously)
```

File: packages/bundle/src/useComposerProps.js [hunk 34]
```diff
@@ -19,10 +19,15 @@ export default function useComposerProps({ attachmentMiddleware, renderMarkdown,
     styleSet
   ]);
 
+  const patchedRenderMarkdown = useMemo(
```
[the remark this answers is not in the document]
Comment (tdurnford) [reply packages/bundle/src/useComposerProps.js:22]: Surprised that wasn't memoized already

File: packages/component/src/Composer.js [hunk 35]
```diff
@@ -131,19 +132,21 @@ function createFocusContext({ mainFocusRef, sendBoxRef }) {
...
       const { current } = ref || {};
 
-      if (current && where === 'sendBoxWithoutKeyboard') {
-        // To not activate the virtual keyboard while changing focus to an input, we will temporarily set it as read-only and flip it back.
-        // https://stackoverflow.com/questions/7610758/prevent-iphone-default-keyboard-when-focusing-an-input/7610923
-        const readOnly = current.getAttribute('readonly');
+      if (current) {
+        if (where === 'sendBoxWithoutKeyboard') {
+          // To not activate the virtual keyboard while changing focus to an input, we will temporarily set it as read-only and flip it back.
+          // https://stackoverflow.com/questions/7610758/prevent-iphone-default-keyboard-when-focusing-an-input/7610923
```
Comment (tdurnford) [inline packages/component/src/Composer.js:138]: I love this

File: packages/component/src/SendBox/IconButton.js [hunk 36]
```diff
@@ -2,21 +2,22 @@ import classNames from 'classnames';
...
   const [{ sendBoxButton: sendBoxButtonStyleSet }] = useStyleSet();
 
   return (
-    <button
-      className={classNames(sendBoxButtonStyleSet + '', className + '')}
+    <AccessibleButton
+      className={classNames(sendBoxButtonStyleSet + '', 'webchat__icon-button', className + '')}
       disabled={disabled}
-      onClick={onClick}
+      onClick={disabled ? undefined : onClick}
```
Comment (tdurnford) [inline packages/component/src/SendBox/IconButton.js:15]: Lol sure you don't want to memoize this? :)

File: packages/component/src/SendBox/SuggestedActions.js (hunk 1 above)
Comment (tdurnford) [reply packages/component/src/SendBox/SuggestedActions.js:101]: Yea I'm good with that.

File: packages/component/src/SendBox/TextBox.js [hunk 37]
```diff
@@ -147,44 +153,56 @@ const TextBox = ({ className }) => {
...
-      onSubmit={handleSubmit}
+      aria-disabled={disabled}
+      className={classNames(
+        ROOT_CSS + '',
+        sendBoxTextAreaStyleSet + '',
+        sendBoxTextBoxStyleSet + '',
+        'webchat__send-box-text-box',
+        className + ''
+      )}
+      onSubmit={disabled ? PREVENT_DEFAULT_HANDLER : handleSubmit}
```
Comment (tdurnford) [inline packages/component/src/SendBox/TextBox.js:164]: useMemo?

File: packages/component/src/SendBox/TextBox.js [hunk 38]
```diff
@@ -147,44 +153,56 @@ const TextBox = ({ className }) => {
...
+                  onChange={disabled ? undefined : handleChange}
+                  onKeyPress={disabled ? undefined : handleKeyPress}
                   placeholder={typeYourMessageString}
+                  readOnly={disabled}
                   ref={sendFocusRef}
                   rows="1"
                   value={textBoxValue}
                 />
-                <div>{textBoxValue + '\n'}</div>
+                <div className="webchat__send-box-text-box__text-area-doppelganger">{textBoxValue + '\n'}</div>
```
Comment (tdurnford) [inline packages/component/src/SendBox/TextBox.js:199]: Text area doppelganger 😂

File: packages/component/src/SendBox/UploadButton.js [hunk 39]
```diff
@@ -25,6 +25,10 @@ const ROOT_CSS = css({
   }
 });
 
+function disabledListener(event) {
```
Comment (tdurnford) [inline packages/component/src/SendBox/UploadButton.js:28]: We should use the same style for 'PREVENT_DEFAULT_HANDLER' to be consistent 

https://github.com/microsoft/BotFramework-WebChat/pull/3150/files#diff-013511e58f42302a34558c03f4cdcdbbR6

File: packages/component/src/Styles/StyleSet/ScrollToEndButton.js (hunk 2 above)
Comment (tdurnford) [reply packages/component/src/Styles/StyleSet/ScrollToEndButton.js:25]: Makes sense.

File: packages/component/src/Styles/defaultStyleOptions.js [hunk 40]
```diff
@@ -16,6 +16,7 @@ const DEFAULT_OPTIONS = {
   paddingRegular: PADDING_REGULAR,
   paddingWide: PADDING_REGULAR * 2,
   subtle: DEFAULT_SUBTLE,
+  zIndex: 0, // "z-index" for the root container of Web Chat. This will form a new stacking context so "z-index" used in children won't pollute.
```
Comment (tdurnford) [inline packages/component/src/Styles/defaultStyleOptions.js:19]: Does `rootZIndex` or `zIndexRoot` make more sense here?

File: packages/component/src/Utils/AccessibleButton.js [hunk 41]
```diff
@@ -0,0 +1,58 @@
...
+
+// Differences between <button> and <AccessibleButton>:
+// - Disable behavior
+//   - When the widget is disabled
+//     - Set "aria-disabled" attribute to "true"
+//     - Set "readonly" attribute
+//     - If the focus is on, don't set "disabled" attribute, until it is blurred
+//       - Otherwise, set "disabled" attribute
+//     - Remove "onClick" handler
+//   - Why we need this
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleButton.js:16]:
```suggestion
//   - Why this is needed
```

File: packages/component/src/Utils/AccessibleButton.js [hunk 42]
```diff
@@ -0,0 +1,58 @@
...
+//     - Browser compatibility: when the widget is disabled, different browser send focus to different places
+//     - When the widget become disabled, it's reasonable to keep the focus on the same widget for an extended period of time
+//       - When the user press TAB after the current widget is disabled, it should jump to the next non-disabled widget
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleButton.js:19]:
```suggestion
//       - When the user presses TAB after the current widget is disabled, it should jump to the next non-disabled widget
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 43]
```diff
@@ -0,0 +1,57 @@
...
+import React, { forwardRef, useRef } from 'react';
+
+import useDisableOnBlurEffect from '../hooks/internal/useDisableOnBlurEffect';
+
+// Differences between <input type="text"> and <AccessibleInputText>:
+// - Disable behavior
+//   - When the widget is disabled
+//     - Set "aria-disabled" attribute to "true"
+//     - Set "readonly" attribute
+//     - If the focus is on, don't set "disabled" attribute, until it is blurred
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:11]:
```suggestion
//     - If the focus is on, don't set "disabled" attribute until it is blurred
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 44]
```diff
@@ -0,0 +1,57 @@
...
+//       - Otherwise, set "disabled" attribute
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:12]:
```suggestion
//       - Otherwise, set "disabled" attribute to true
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 45]
```diff
@@ -0,0 +1,57 @@
...
+//     - Remove "onChange" handler
+//   - Why we need this
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:14]:
```suggestion
//   - Why this is needed
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 46]
```diff
@@ -0,0 +1,57 @@
...
+//     - Browser compatibility: when the widget is disabled, different browser send focus to different places
+//     - When the widget become disabled, it's reasonable to keep the focus on the same widget for an extended period of time
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:16]:
```suggestion
//     - When the widget is disabled, it's reasonable to keep the focus on the same widget for an extended period of time
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 47]
```diff
@@ -0,0 +1,57 @@
...
+//       - When the user press TAB after the current widget is disabled, it should jump to the next non-disabled widget
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:17]:
```suggestion
//       - When the user presses TAB after the current widget is disabled, it should jump to the next non-disabled widget
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 48]
```diff
@@ -0,0 +1,57 @@
...
+
+// Developers using this accessible widget will need to:
+// - Style the disabled widget themselves, using CSS query `:disabled, [aria-disabled="true"] {}`
+// - Modify all code that check disabled through "disabled" attribute to use aria-disabled="true" instead
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:21]:
```suggestion
// - Modify all the code that checks disabled through the "disabled" attribute to use aria-disabled="true" instead
```

File: packages/component/src/Utils/AccessibleInputText.js [hunk 49]
```diff
@@ -0,0 +1,57 @@
...
+  disabled: undefined,
+  onChange: undefined
+};
+
+AccessibleInputText.displayName = 'AccessibleInputText';
+
+AccessibleInputText.propTypes = {
+  disabled: PropTypes.bool,
+  onChange: PropTypes.func,
+  type: PropTypes.oneOf(['text']).isRequired
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleInputText.js:54]: Why are you using `oneOf` if there is only one item?

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 50]
```diff
@@ -0,0 +1,55 @@
...
+import React, { forwardRef, useRef } from 'react';
+
+import useDisableOnBlurEffect from '../hooks/internal/useDisableOnBlurEffect';
+
+// Differences between <textarea> and <AccessibleTextArea>:
+// - Disable behavior
+//   - When the widget is disabled
+//     - Set "aria-disabled" attribute to "true"
+//     - Set "readonly" attribute
+//     - If the focus is on, don't set "disabled" attribute, until it is blurred
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:11]:
```suggestion
//     - If the focus is on, don't set "disabled" attribute until it is blurred
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 51]
```diff
@@ -0,0 +1,55 @@
...
+//       - Otherwise, set "disabled" attribute
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:12]:
```suggestion
//       - Otherwise, set "disabled" attribute to `true`
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 52]
```diff
@@ -0,0 +1,55 @@
...
+//     - Remove "onChange" handler
+//   - Why we need this
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:14]:
```suggestion
//   - Why this is needed
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 53]
```diff
@@ -0,0 +1,55 @@
...
+//     - Browser compatibility: when the widget is disabled, different browser send focus to different places
+//     - When the widget become disabled, it's reasonable to keep the focus on the same widget for an extended period of time
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:16]:
```suggestion
//     - When the widget is disabled, it's reasonable to keep the focus on the same widget for an extended period of time
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 54]
```diff
@@ -0,0 +1,55 @@
...
+//       - When the user press TAB after the current widget is disabled, it should jump to the next non-disabled widget
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:17]:
```suggestion
//       - When the user presses TAB after the current widget is disabled, it should move the focus to the next non-disabled widget
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 55]
```diff
@@ -0,0 +1,55 @@
...
+
+// Developers using this accessible widget will need to:
+// - Style the disabled widget themselves, using CSS query `:disabled, [aria-disabled="true"] {}`
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:20]:
```suggestion
// - Style the disabled widget themselves using CSS query `:disabled, [aria-disabled="true"] {}`
```

File: packages/component/src/Utils/AccessibleTextArea.js [hunk 56]
```diff
@@ -0,0 +1,55 @@
...
+// - Modify all code that check disabled through "disabled" attribute to use aria-disabled="true" instead
```
Comment (tdurnford) [inline packages/component/src/Utils/AccessibleTextArea.js:21]:
```suggestion
// - Modify all the code that checks disabled through the "disabled" attribute to use aria-disabled="true" instead
```

File: packages/component/src/hooks/internal/useDisableOnBlurEffect.js [hunk 57]
```diff
@@ -0,0 +1,30 @@
...
+      const { current } = targetRef;
+
+      if (current) {
+        if (document.activeElement !== current) {
+          current.setAttribute('disabled', 'disabled');
+
+          return () => current.removeAttribute('disabled');
+        }
+
+        const handler = () => current.setAttribute('disabled', 'disabled');
```
Comment (tdurnford) [inline packages/component/src/hooks/internal/useDisableOnBlurEffect.js:19]: Should you move this out of the useEffect hook so you can use useCallback?

File: docs/ACCESSIBILITY.md (hunk 21 above)
Comment (compulim) [reply docs/ACCESSIBILITY.md:85]: Invisible to eyes, i.e. (user agent) CSS is not applied, but somehow you know it's on the parent because when you <kbd>TAB</kbd>, you know the order... like quantum entanglement. 😁

Like me find a better phrase or expand it.

File: docs/ACCESSIBILITY.md (hunk 31 above)
Comment (compulim) [reply docs/ACCESSIBILITY.md:123]: Yes, soft keyboard are usually on mobile.

File: packages/component/src/Composer.js (hunk 35 above)
Comment (compulim) [reply packages/component/src/Composer.js:138]: A hack that have been working for last 9 years. 😂

File: packages/component/src/SendBox/TextBox.js (hunk 38 above)
Comment (compulim) [reply packages/component/src/SendBox/TextBox.js:199]: This name is perfect, IMO.

File: packages/bundle/src/useComposerProps.js (hunk 34 above)
[the remark this answers is not in the document]
Comment (compulim) [reply packages/bundle/src/useComposerProps.js:22]: Not to mention using `remarked` to strip Markdown syntax is one of the worst perf offender. Need to find a better way out later.

File: docs/ACCESSIBILITY.md (hunk 21 above)
Comment (compulim) [reply docs/ACCESSIBILITY.md]: Change this into a table, easier to consume.

It showed 4 different variations across 6 desktop browsers, how fragmented it is.

File: docs/ACCESSIBILITY.md (hunk 23 above)
Comment (compulim) [reply docs/ACCESSIBILITY.md]: Changed to table format.

File: packages/component/src/SendBox/IconButton.js (hunk 36 above)
Comment (compulim) [reply packages/component/src/SendBox/IconButton.js:15]: Yap, for two reasons:

1. It doesn't save any computation time, while using more memory
1. Given `disabled` and `onClick` are unchanged, re-render won't introduce unneeded changes (waste render)

I really think hard about it when you raise this question. On the other hand, I am thinking to memoize result from `classNames()`. 😂

File: packages/component/src/Utils/AccessibleInputText.js (hunk 49 above)
Comment (compulim) [reply packages/component/src/Utils/AccessibleInputText.js:54]: Since this component is enhancing `<input type="text">` but not `<input type="radio">`, I want to make sure user of this component pass `type="text"`, but not something else.

But we can't write:

```js
AccessibleInputText.propTypes = {
  type: 'text'
};
```

So the easiest is `PropTypes.oneOf(['text']).isRequired`.

While reading some docs on this, we should change all `children: PropTypes.any` to `children: PropTypes.element`.

File: packages/component/src/hooks/internal/useDisableOnBlurEffect.js (hunk 57 above)
Comment (compulim) [reply packages/component/src/hooks/internal/useDisableOnBlurEffect.js:19]: When I work with `useCallback` or `useMemo`, I always think about our gains. For example, less waste-render, less reconciliation, reduced computation (thru increased memory usage), etc.

If we use `useMemo` with similar memory usage characteristics, the code would become:

```js
export default function useDisableOnBlurEffect(targetRef, disabled) {
  const disabledHandler = useMemo(
    () => disabled && targetRef.current && (() => targetRef.current.setAttribute('disabled', 'disabled')),
    [disabled, targetRef]
  );

  useEffect(() => {
    if (disabled) {
      const { current } = targetRef;

      if (current) {
        if (document.activeElement !== current) {
          current.setAttribute('disabled', 'disabled');

          return () => current.removeAttribute('disabled');
        }

        current.addEventListener('blur', disabledHandler);

        return () => {
          current.removeAttribute('disabled');
          current.removeEventListener('blur', disabledHandler);
        };
      }
    }
  }, [disabled, disabledHandler, targetRef]);
}
```

IMO, it seems a bit over-engineering since the gain is not significant to non-existent, I believe. (See the deps array, they are the same, so I believe no gains.)

If I simplify the code a bit, so it don't look over-engineering:

```js
export default function useDisableOnBlurEffect(targetRef, disabled) {
  const disabledHandler = useMemo(
    () => targetRef.current && (() => targetRef.current.setAttribute('disabled', 'disabled')),
    [targetRef]
  );

  useEffect(() => {
    if (disabled) {
      const { current } = targetRef;

      if (current) {
        if (document.activeElement !== current) {
          current.setAttribute('disabled', 'disabled');

          return () => current.removeAttribute('disabled');
        }

        current.addEventListener('blur', disabledHandler);

        return () => {
          current.removeAttribute('disabled');
          current.removeEventListener('blur', disabledHandler);
        };
      }
    }
  }, [disabled, disabledHandler, targetRef]);
}
```

Then:

- Event handler is always in memory, saving function construction time but increasing heap size
- I believe most widget is 80% enabled, 20% disabled, that means 80% of time we are using more unnecessary memory
- If `disabled` is flipped very frequently, this approach will have some gain on perf, but we aren't flipping it very often

I end up using `bind`:

```
function disableElement(element) {
  element.setAttribute('disabled', 'disabled');
}

export default function useDisableOnBlurEffect(targetRef, disabled) {
  useEffect(() => {
    if (disabled) {
      const { current } = targetRef;

      if (current) {
        if (document.activeElement !== current) {
          current.setAttribute('disabled', 'disabled');

          return () => current.removeAttribute('disabled');
        }

        const blurHandler = disableElement.bind(current);

        current.addEventListener('blur', blurHandler);

        return () => {
          current.removeAttribute('disabled');
          current.removeEventListener('blur', blurHandler);
        };
      }
    }
  }, [disabled, targetRef]);
}
```

I think this would reduce memory usage, and according to [jsperf.com](https://jsperf.com/bind-vs-closure-setup/58), this has same perf compare to closure.

File: packages/component/src/Styles/defaultStyleOptions.js (hunk 40 above)
Comment (compulim) [reply packages/component/src/Styles/defaultStyleOptions.js:19]: Renamed to `rootZIndex` to match `rootHeight`/`rootWidth` some where below.

File: packages/component/src/SendBox/TextBox.js (hunk 37 above)
Comment (compulim) [reply packages/component/src/SendBox/TextBox.js:164]: Seems overkill for `useMemo` on a ternary operator. 😁

File: CHANGELOG.md (hunk 7 above)
Comment (compulim) [reply CHANGELOG.md:137]: Will add the changelog line once I have `README.md` ready. 😉
