### PR TITLE
Rendering spaces for markdown format. Fixes #596

### LINKED ISSUE #596: Empty message bubbles render incorrectly
image

### PR DESCRIPTION
**Pull request by reyesrico**
Rendering spaces for markdown format. Fixes #596

### CODE REVIEW

File: src/FormattedText.tsx [hunk 1]
```diff
@@ -54,11 +54,18 @@ const renderMarkdown = (
...
+        const src = text
                 // convert <br> tags to blank lines for markdown
-                 .replace(/<br\s*\/?>/ig, '\r\n\r\n')
+                .replace(/<br\s*\/?>/ig, '\r\n\r\n')
                 // URL encode all links
                  .replace(/\[(.*?)\]\((.*?)\)/ig, (match, text, url) => `[${text}](${markdownIt.normalizeLink(url)})`);
-    const __html = markdownIt.render(src);
+        __html = markdownIt.render(src);        
+    } else {
+        __html = text.replace(/ */, '\u00A0');
```
Comment (danmarshall) [inline src/FormattedText.tsx]: Can you add a comment about what the `\u00A0` character is?

File: test/commands_map.ts [hunk 2]
```diff
@@ -356,6 +356,14 @@ var commands_map: CommandValuesMap = {
             sendActivity(conversationId, server_content.receipt_card);
         }
     },
+    "text-empty": {
+        client: function () {
+            return true;
```
Comment (danmarshall) [inline test/commands_map.ts]: can you verify that there is a bubble? Test should fail if we run against current code.
