### PR TITLE
Fix IE11 on clicking on transcript will throw exception of `matches`

### LINKED ISSUE #4386: IE11: Click on Adaptive Cards should not throw exception
## Screenshots

image

## Version

`4.15.3-0`

## Describe the bug

`HTMLElement.matches` needs to be vendor-prefixed to `HTMLElement.msMatchesSelector` in IE11.

## Steps to reproduce

1. Talk to MockBot
2. Type `card breakfast`
3. Click on the "Snooze" button on the card

## Expected behavior

It should not throw exceptions.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #4386.

### Fixed

-  Fixes [#4386](https://github.com/microsoft/BotFramework-WebChat/issues/4386). Clicking on Adaptive Cards should not throw exception under IE11, by [@compulim](https://github.com/compulim), in PR [#4387](https://github.com/microsoft/BotFramework-WebChat/pull/4387), also fixed:
   -  Prop type warning should not be shown for `<ActivityRow>`

## Description

`HTMLElement.matches` needs to be vendor-prefixed to `HTMLElement.msMatchesSelector` in IE11.

## Specific Changes

- Updated all occurrences of `HTMLElement.matches` to fallback to `HTMLElement.msMatchesSelector`
- Added `displayName` to some React component for debuggability
- Changed `children: PropTypes` to `any` as the previous combination actually showing warning on wrong prop type

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] I have updated documentation

## Review Checklist

> This section is for contributors to review your work.

-  [x] ~Accessibility reviewed (tab order, content readability, alt text, color contrast)~
-  [x] Browser and platform compatibilities reviewed
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] ~Tests reviewed (coverage, legitimacy)~

### CODE REVIEW

File: packages/component/src/BasicTranscript.tsx [hunk 1]
```diff
@@ -590,6 +590,8 @@ InternalTranscript.defaultProps = {
   className: ''
 };
 
+InternalTranscript.displayName = 'InternalTranscript';
```
Comment (compulim) [inline packages/component/src/BasicTranscript.tsx:593]: Adding `displayName` for debuggability.

File: packages/component/src/Transcript/ActivityRow.tsx [hunk 2]
```diff
@@ -117,7 +119,7 @@ ActivityRow.propTypes = {
       'webchat:fallback-text': PropTypes.string
     })
   }).isRequired,
-  children: PropTypes.oneOfType([PropTypes.element, PropTypes.arrayOf(PropTypes.element)])
+  children: PropTypes.any
```
Comment (compulim) [inline packages/component/src/Transcript/ActivityRow.tsx:122]: Prop type warning should not be shown.
