### PR TITLE
Compatibility fix for IE11

### LINKED ISSUE #2972: IE11: Fixing polyfills and behaviors
## Version

`master` for R8.

## Describe the bug

Some features are not implemented in IE11, need to bring in a polyfill or use legacy way to do stuff.

- `Set` is not a full implementation, missing `Symbol.iterator`
   - Use `core-js` to polyfill `Set`
- `CustomEvent.constructor` is missing
   - Use `document.createEvent` and `Event.initEvent` instead

## Steps to reproduce

Host Web Chat on IE11.

## Expected behavior

Basic operations are working.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #2972.

## Changelog Entry

-  Fixes [#2972](https://github.com/microsoft/BotFramework-WebChat/issues/2972). Compatibility fix for IE11, by [@compulim](https://github.com/compulim) in PR [#2973](https://github.com/microsoft/BotFramework-WebChat/pull/2973)

## Description

Some APIs we used are lacking in IE11, requires polyfill or use legacy approach.

## Specific Changes

- `Set` is not a full implementation, missing `Symbol.iterator`
   - Use `core-js` to polyfill `Set`
- `CustomEvent.constructor` is missing
   - Use `document.createEvent` and `Event.initEvent` instead

---

-  [x] Testing Added
   -  IE11 requires manual testing

### CODE REVIEW

File: packages/component/src/hooks/useSubmitSendBox.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ export default function useSubmitSendBox() {
 
   return useCallback(
     (...args) => {
-      const [method = 'keyboard'] = args;
+      // We cannot use spread operator as it broke in Angular.
```
Comment (corinagum) [inline packages/component/src/hooks/useSubmitSendBox.js]:
```suggestion
      // We cannot use spread operator as it broken in Angular.
```
