### PR TITLE
#2658 Fix rendering of markdown images in IE11

### LINKED ISSUE #2658: IE11 does not respect max-width of markdown images
Related to #1944 

## Steps to reproduce

1. Open a bot in IE11
1. Use a bot that sends a markdown image to the user
1. Note that there's a large gap above the sendbox

## Expected behavior

Image should not cause empty space after commands.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by corinagum**
Fixes #2658 

## Changelog Entry

-  Fixes [#2658](https://github.com/microsoft/BotFramework-WebChat/issues/2658). Fix rendering of markdown images in IE11, by [@corinagum](https://github.com/corinagum) in PR [#2659](https://github.com/microsoft/BotFramework-WebChat/pull/2659)

## Description

Before (IE11):
image

After (IE11):
image

## Specific Changes

 

---

-  [ ] Testing Added

### CODE REVIEW

File: packages/component/src/Styles/StyleSet/TextContent.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /* eslint no-magic-numbers: "off" */
 
-export default function createTextContentStyle({ bubbleMinHeight, primaryFont, paddingRegular }) {
+export default function createTextContentStyle({ bubbleMinHeight, bubbleMaxWidth, primaryFont, paddingRegular }) {
```
Comment (compulim) [inline packages/component/src/Styles/StyleSet/TextContent.js]:
```suggestion
export default function createTextContentStyle({ bubbleMaxWidth, bubbleMinHeight, primaryFont, paddingRegular }) {
```

**Comment by corinagum** [comment]
@compulim I added it to our MockBot update issue: https://github.com/microsoft/BotFramework-WebChat/issues/2657
