### PR TITLE
Fix Suggested Actions accessibility

### LINKED ISSUE #2713: Accessibility: Suggested actions are not narrated
## Version

`master` (4.7 RC)

## Describe the bug

Suggested actions are not narrated via Assistive Technology.

## Steps to reproduce

1. Turn on Narrator
1. Use Edge and browse to Web Chat on MockBot
1. Type "suggested-actions"

## Expected behavior

AT should narrate the content of suggested actions.

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by corinagum**
> Fixes #2713.

### Fixed

-  Fixes [#2713](https://github.com/microsoft/BotFramework-WebChat/issues/2713). Suggested actions container should persist for AT, by [@corinagum](https://github.com/corinagum) in PR [#2712](https://github.com/microsoft/BotFramework-WebChat/pull/2712)

## Description

Narration of suggested actions is done via `aria-live="polite"`.

Today, the suggested actions container does not exists when the suggested actions are received, thus, AT do not narrate the suggested actions because AT is designed not to narrate new content in the `aria-live="polite"` container. It only narrate changed contents.

## Specific Changes

- Modify `SuggestedActions.js` to show a persisted container even there are no suggested actions.

---

-  [x] ~Testing Added~ (Will manual test)
   1. Turn on AT
   1. Type "suggested-actions"
   1. Expect: AT should narrate the content of suggested actions

### CODE REVIEW

File: packages/component/src/SendBox/SuggestedActions.js [hunk 1]
```diff
@@ -67,7 +71,7 @@ const SuggestedActions = ({ className, suggestedActions = [] }) => {
 
   if (suggestedActionLayout === 'stacked') {
     return (
-      <div aria-label=" " aria-live="polite" role="status">
+      <div aria-label="test" aria-live="polite" role="status">
```
Comment (tdurnford) [inline packages/component/src/SendBox/SuggestedActions.js]: Do we still want the aria-label to be test?

Comment (corinagum) [reply packages/component/src/SendBox/SuggestedActions.js]: oops
thanks

File: packages/component/src/SendBox/SuggestedActions.js [hunk 2]
```diff
@@ -49,7 +49,11 @@ const SuggestedActions = ({ className, suggestedActions = [] }) => {
     (suggestedActions.length ? suggestedActionsContentText : suggestedActionsEmptyText);
 
   if (!suggestedActions.length) {
-    return false;
+    return (
+      <div aria-label="test" aria-live="polite" role="status">
```
Comment (tdurnford) [inline packages/component/src/SendBox/SuggestedActions.js]: aria-label is `"test"` here as well.
