### PR TITLE
Fixed batched livestream activities are not recognized in the same session

### LINKED ISSUE #5439: Two batched incoming livestream activities should be identified as same session
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Development build

### Which distribution are you using Web Chat from?

Unrelated

### Which hosting environment does this issue primarily affect?

Others or unrelated

### Which browsers and platforms do the issue happened?

Others or unrelated

### Which area does this issue affect?

Chat history

### Which theme pack does this issue affect?

I did not test it on other theme packs

### What is the public URL for the website?

https://compulim.github.io/webchat-loader

### Please describe the bug

When 2 livestream activities of the same session are being sent as a batch, they are not recognized as in the same session.

### Do you see any errors in console log?

```js

```

### How to reproduce the issue?

Replay this transcript.

```json
[
  {
    "activity": {
      "channelData": {
        "streamSequence": 1,
        "streamType": "informative"
      },
      "from": {
        "id": "u-00001",
        "name": "Bot",
        "role": "bot"
      },
      "id": "t-00001",
      "text": "Nisi elit quis nisi consectetur.",
      "type": "typing"
    }
  },
  {
    "activity": {
      "channelData": {
        "streamId": "t-00001",
        "streamType": "final"
      },
      "from": {
        "id": "u-00001",
        "name": "Bot",
        "role": "bot"
      },
      "id": "53294dea-749f-412e-a9b9-a057f7503d49",
      "text": "Ex nulla pariatur deserunt commodo enim laborum consequat officia proident.",
      "type": "message"
    }
  }
]
```

### What do you expect?

One activity is displayed.

### What actually happened?

2 activities are shown.

### Do you have any screenshots or recordings to repro the issue?

_No response_

### Adaptive Card JSON

```json

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by compulim**
> Fixes #5439.

### Fixed

- Fixed [#5439](https://github.com/microsoft/BotFramework-WebChat/issues/5439). Fixed batched livestream activities are not recognized in the same session, in PR [#XXX](https://github.com/microsoft/BotFramework-WebChat/pull/XXX)

## Description

On every batch of incoming activities, activity keyer will recreate the keypair map.

Activity keyer will read from the old map and write to the new one. Writing to the new one ensures each render loop is clean of resource leak.

If activities are batched, activity keyer may not found the key as the key could be added in the same round.

This pull request fixed the activity keyer by reading from both new and old map.

## Design

If unknown reasons, we cannot reproduce batched activities in the test suite. Or in other words, we do not know why the activities are batched.

We are using Redux store directly to inject activities, before Web Chat is mounted. So, first render will have 2 activities batched.

## Specific Changes

- Fixed `ActivityKeyerComposer` to read from both new and old map

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [x] ~Accessibility reviewed (tab order, content readability, alt text, color contrast)~
-  [x] ~Browser and platform compatibilities reviewed~
-  [x] ~CSS styles reviewed (minimal rules, no `z-index`)~
-  [x] ~Documents reviewed (docs, samples, live demo)~
-  [x] ~Internationalization reviewed (strings, unit formatting)~
-  [x] ~`package.json` and `package-lock.json` reviewed~
-  [x] ~Security reviewed (no data URIs, check for nonce leak)~
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/api/src/providers/ActivityKeyer/ActivityKeyerComposer.tsx [hunk 1]
```diff
@@ -75,10 +75,13 @@ const ActivityKeyerComposer = ({ children }: Readonly<{ children?: ReactNode | u
...
-        (clientActivityId && clientActivityIdToKeyMap.get(clientActivityId)) ||
-        (typingActivityId && activityIdToKeyMap.get(typingActivityId)) ||
-        (activityId && activityIdToKeyMap.get(activityId)) ||
+        (clientActivityId &&
+          (clientActivityIdToKeyMap.get(clientActivityId) || nextClientActivityIdToKeyMap.get(clientActivityId))) ||
+        (typingActivityId &&
+          (activityIdToKeyMap.get(typingActivityId) || nextActivityIdToKeyMap.get(typingActivityId))) ||
+        (activityId && (activityIdToKeyMap.get(activityId) || nextActivityIdToKeyMap.get(activityId))) ||
         activityToKeyMap.get(activity) ||
+        nextActivityToKeyMap.get(activity) ||
```
Comment (OEvgeny) [inline packages/api/src/providers/ActivityKeyer/ActivityKeyerComposer.tsx:84]: As expected next vs previous. Good thing it is now fixed!

**Review by OEvgeny — APPROVED** [review]
