### PR TITLE
Fixed AdaptiveCards Update Issues

### LINKED ISSUE #2068: Web Chat throwing 'adaptiveCard.validate is not a function' error
## Screenshots
image

## Version
Version: 0.0.0-0
Local build from master branch

## Describe the bug
In the most resent release of AdaptiveCards - v1.2 - the developers removed the validate function from the renderer.  Web Chat updated the AdaptiveCards dependency in PR https://github.com/microsoft/BotFramework-WebChat/pull/2064 to v1.2; however, the [AdaptiveCardRenderer](https://github.com/microsoft/BotFramework-WebChat/blob/4f21f0bf5e5d2cfa0e5304bc6c37c9c95357fc29/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardRenderer.js#L120) component still uses the validate function. As a result, Web Chat is throwing an  'adaptiveCard.validate is not a function' error.

> The CardElement.validate() and Action.validate() methods have been REMOVED, replaced with CardObject.validateProperties() and CardObject.internalValidateProperties(context: ValidationContext). Custom elements and actions now must override internalValidateProperties and add validation failures as appropriate to the context object passed as a parameter using its addFailure method. Be sure to always call super.internalValidateProperties(context) in your override.

https://www.npmjs.com/package/adaptivecards#breaking-changes

In addition to reconfiguring the AdaptiveCardRenderer component, AdaptiveCard tests should be added to prevent errors like this in the future. 

## To Reproduce
Send an AdaptiveCard to Web Chat

```javascript
const card = CardFactory.adaptiveCard({
  "type": "AdaptiveCard",
  "body": [
      {
          "type": "TextBlock",
          "text": "AdaptiveCard"
      }
  ],
  "actions": [
      {
          "type": "Action.OpenUrl",
          "title": "Action.OpenUrl",
          "url": "https://microsoft.com"
      }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.1"
});

await context.sendActivity({ attachments: [card]});
```

[Bug]

### PR DESCRIPTION
**Pull request by tdurnford**
Fixes #2068 

Fix [#2068](https://github.com/Microsoft/BotFramework-WebChat/issues/2068). Fixed AdaptiveCards validate and speak issues, by [@tdurnford](https://github.com/tdurnford) in PR [#2075](https://github.com/Microsoft/BotFramework-WebChat/pull/2075)

 ## Specific Changes	
Changed `CardObject.validate()` to `CardObject.validateProperties()` in the AdaptiveCardRenderer component per AdaptiveCard's breaking-changes documentation. Also modified how the AdaptiveCardBuilder class handles speaking text since the speak attribute was removed from TextBlocks in the newest version of AdaptiveCards.

### CODE REVIEW

File: packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardBuilder.ts [hunk 1]
```diff
@@ -89,7 +89,7 @@ export default class AdaptiveCardBuilder {
         textblock[prop] = template[prop];
       }
 
-      textblock.speak = text;
+      this.card.speak += `${text} `;
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardBuilder.ts]: Could you explain a bit about this?

I am only scanning thru the code, I thought concatenating a string should look something like ``speak += ` ${text}`;``, with a space prepended to it, instead of having the space appended to it, like ``speak += `${text} `;``.

Comment (tdurnford) [reply packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardBuilder.ts]: I was amusing the speak attribute would be an empty string and since it's only being modified there it made more sense to me to append the space to the end. I think either would be fine. Do you have a preference?

**Comment by corinagum** [comment]
🎊
