### PR TITLE
Fix vertical spacing of ConnectivityStatus when empty

### LINKED ISSUE #1934: Should not have persisted padding below transcript
## Repro steps

1. Navigate to https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/
2. Wait until it is connected
3. Type "carousel" 5 times

Expected: no padding below transcript

Actual:
image

Please add a test to verify the fix is in-place.

### PR DESCRIPTION
**Pull request by corinagum**
Fix #1934 
This PR recaptures several of the tests. 
image

note that 'Just now' text previously had extra spacing on it. That has been removed in this PR.

### CODE REVIEW

File: packages/component/src/SendBox/ConnectivityStatus.js [hunk 1]
```diff
@@ -55,51 +55,39 @@ export default connectConnectivityStatus(
...
-            <React.Fragment>
+            </div>
+          : connectivityStatus === 'sagaerror' ?
+            <div className={ styleSet.errorNotification }>
               <ErrorNotificationIcon />
               { localize('RENDER_ERROR_NOTIFICATION', language) }
-            </React.Fragment>
+            </div>
+          : connectivityStatus === 'reconnected' || connectivityStatus === 'connected' &&
+          <div className={ styleSet.connectivityNotificationEmpty } />
```
Comment (compulim) [inline packages/component/src/SendBox/ConnectivityStatus.js]: We should return `false` here.

File: packages/component/src/Styles/StyleSet/ConnectivityNotificationEmpty.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
+export default function ({
```
Comment (compulim) [inline packages/component/src/Styles/StyleSet/ConnectivityNotificationEmpty.js]: This is probably unused.

File: CHANGELOG.md [hunk 3]
```diff
@@ -36,6 +36,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - Fix [#1789](https://github.com/Microsoft/BotFramework-WebChat/issues/1789). Focus send box after message is being sent, by [@corinagum](https://github.com/corinagum) in PR [#1915](https://github.com/Microsoft/BotFramework-WebChat/pull/1915)
 - Fix [#1920](https://github.com/Microsoft/BotFramework-WebChat/issues/1920). Added disabled property to send button, by [@tdurnford](https://github.com/tdurnford) in PR [#1922](https://github.com/Microsoft/BotFramework-WebChat/pull/1922)
 - Fix [#1525](https://github.com/Microsoft/BotFramework-WebChat/issues/1525). Add JavaScript error Offline UI, by [@corinagum](https://github.com/corinagum) in PR [#1927](https://github.com/Microsoft/BotFramework-WebChat/pull/1927)
+- Fix [#1934](https://github.com/Microsoft/BotFramework-WebChat/issues/1934). Fix spacing of empty ConnectivityStatus component, by [@corinagum](https://github.com/corinagum) in PR [#XXX](https://github.com/Microsoft/BotFramework-WebChat/pull/XXX)
```
Comment (compulim) [inline CHANGELOG.md]: XXX
