### PR TITLE
Styles: add shadow DOM support

### LINKED ISSUE #5194: Webchat does not render correctly when added to a Web Component/shadowRoot
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Others or unrelated

### Which theme pack does this issue affect?

I did not test it on other theme packs

### What is the public URL for the website?

_No response_

### Please describe the bug

Attempting to render Web Chat inside a Web Component does not appear to work, and renders in a broken state:
image

I'm presuming this could be from the CSS-in-JS not working correctly within a Shadow DOM? Are there any workarounds for this? 
```
<!DOCTYPE html>
<html>
  <head>
    <script
      crossorigin="anonymous"
      src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"
    ></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat-container {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <webchat-element></webchat-element>

    <script>
      class WebChatElement extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({ mode: 'open' });
        }

        connectedCallback() {
          const container = document.createElement('div');
          container.id = 'webchat';
          container.style.height = '100%';
          container.style.width = '100%';
          this.shadowRoot.appendChild(container);

          window.WebChat.renderWebChat(
            {
              directLine: window.WebChat.createDirectLine({
                token: 'YOUR_DIRECT_LINE_TOKEN'
              }),
              userID: 'YOUR_USER_ID',
              username: 'Web Chat User',
              locale: 'en-US'
            },
            container
          );
        }
      }

      customElements.define('webchat-element', WebChatElement);
    </script>
  </body>
</html>
```

### Do you see any errors in console log?

```js
No console errors
```

### How to reproduce the issue?

Reproduce the provided html example above

### What do you expect?

That the webchat should still render correctly with it's CSS

### What actually happened?

The webchat does not appear to render with it's CSS

### Do you have any screenshots or recordings to repro the issue?

_No response_

### Adaptive Card JSON

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by OEvgeny**
> Fixes #5194

## Changelog Entry

- (Experimental) Added support for using WebChat inside a shadow DOM, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
  - Added `styleOptions.stylesRoot` property allowing users to specify the root node where WebChat styles should be placed, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
  - Added the `ThemeProvider.styles` property, allowing theme packages to place styles into the same root node as WebChat, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
  - Added `nonce` for Fluent and `react-scroll-to-bottom` injected styles, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
  - Updated `react-scroll-to-bottom` to version `4.2.1-main.53844f5`, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
  - Updated `react-film` to version `3.1.1-main.f623bf6`, in PR [#5196](https://github.com/microsoft/BotFramework-WebChat/pull/5196), by [@OEvgeny](https://github.com/OEvgeny)
 
## Description

The change allows to mount webchat inside of shadow roots by providing the container for emotion and Fluent styles.

TODO:
- [x] `react-scroll-to-bottom` styles: need to update emotion usage on the library side and update the library.
- [x] `react-film` styles: need to update emotion usage on the library side and update the library.
## Design
The design encapsulates related code into dedicated modules and centralizes style injection.

With the new approach, the Fluent theme passes styles down to WebChat, which then determines the appropriate location to inject these styles.

Instead of calculating the root node before mounting the rest of the component tree, we let user specify the desired location for the styles.

## Specific Changes

- Reworked `useStyleToEmotionObject`
- Added `useInjectStyles`
- Refactored `useStyleToEmotionObject` usage
- Added the `styles` prop to `ThemeProvider`
- Renamed `ContextType` to `ThemeContextType`
- Fluent: reworked `injectStyles` to `createStyles`
- Added `styleOptions.stylesRoot`
- Added tests

## -

-

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] ~I have updated documentation~

## Review Checklist

> This section is for contributors to review your work.

-  [ ] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [ ] Browser and platform compatibilities reviewed
-  [ ] CSS styles reviewed (minimal rules, no `z-index`)
-  [ ] Documents reviewed (docs, samples, live demo)
-  [ ] Internationalization reviewed (strings, unit formatting)
-  [ ] `package.json` and `package-lock.json` reviewed
-  [ ] Security reviewed (no data URIs, check for nonce leak)
-  [ ] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/api/src/StyleOptions.ts [hunk 1]
```diff
@@ -847,6 +847,13 @@ type StyleOptions = {
    * @default 2000
    */
   maxMessageLength?: number;
+
+  /**
+   * A node used for WebChat styles to be placed into
```
Comment (OEvgeny) [inline packages/api/src/StyleOptions.ts:852]:
```suggestion
   * The node used for WebChat styles to be placed into
```

File: packages/component/src/providers/Theme/private/Context.ts [hunk 2]
```diff
@@ -18,7 +18,7 @@ import { createContext } from 'react';
 const EMPTY_ARRAY = Object.freeze([] as const);
 const EMPTY_OBJECT = Object.freeze({} as const);
 
-export type ContextType = {
+export type ThemeContextType = {
```
Comment (OEvgeny) [inline packages/component/src/providers/Theme/private/Context.ts:21]: Renamed as it gets bundled into types as `ContextType$1` otherwise

File: packages/component/src/hooks/internal/styleToEmotionObject.tsx [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import React, { createContext, createRef, type ReactNode, type RefObject, useCallback, useContext } from 'react';
+import { useRefFrom } from 'use-ref-from';
+import { hooks } from 'botframework-webchat-api';
+import useEmotion from './useEmotion';
+
+const { useStyleOptions } = hooks;
+
+const styleToEmotionObjectContext = createContext<RefObject<(...args: any[]) => string>>(createRef());
+
+export const StyleToEmotionObjectProvider = ({ children, nonce }: Readonly<{ children: ReactNode; nonce: string }>) => {
```
Comment (compulim) [inline packages/component/src/hooks/internal/styleToEmotionObject.tsx:10]: Could we turn this into our `<XXXProvider>` pattern? Like, the `<ActivityKeyerComposer>`. But I know the boilerplate code could be improved if we set up a standard pattern.

File: packages/component/src/providers/Theme/private/Context.ts (hunk 2 above)
Comment (compulim) [reply packages/component/src/providers/Theme/private/Context.ts:21]: Good to know. We have tons. 🙂

File: packages/component/src/providers/Theme/ThemeProvider.tsx [hunk 4]
```diff
@@ -108,6 +109,7 @@ const ThemeProvider = ({
       sendBoxMiddleware: mergedSendBoxMiddleware,
       sendBoxToolbarMiddleware: mergedSendBoxToolbarMiddleware,
       styleOptions: mergedStyleOptions,
+      styles,
```
Comment (compulim) [inline packages/component/src/providers/Theme/ThemeProvider.tsx:112]: I think we should cascade/merge `styles` from other cascading `<ThemeProvider>`.

File: packages/fluent-theme/tsup.config.ts [hunk 5]
```diff
@@ -2,7 +2,7 @@ import { join } from 'path';
 import { defineConfig } from 'tsup';
 import { fileURLToPath } from 'url';
 import baseConfig from '../../tsup.base.config';
-import { injectedStyles as injectedStylesPlaceholder } from './src/styles/injectStyle';
+import { injectedStyles as injectedStylesPlaceholder } from './src/styles/createStyles';
```
Comment (compulim) [inline packages/fluent-theme/tsup.config.ts:5]: Maybe rename?

File: packages/component/src/hooks/internal/styleToEmotionObject.tsx (hunk 3 above)
Comment (compulim) [reply packages/component/src/hooks/internal/styleToEmotionObject.tsx:10]: Maybe a barrel file (`index.ts`) for the `<XXXProvider>` pattern so we have a single entry point. I forgot what come up with our last discussion about this.

File: packages/component/src/BasicTranscript.tsx [hunk 6]
```diff
@@ -843,10 +844,14 @@ const BasicTranscript: FC<BasicTranscriptProps> = ({ className }) => {
   const containerRef = useRef<HTMLDivElement>();
 
   const scroller = useScroller(activityElementMapRef);
+  const nonce = useNonce();
```
Comment (OEvgeny) [inline packages/component/src/BasicTranscript.tsx:847]:
```suggestion
  const nonce = useNonce();
  const scroller = useScroller(activityElementMapRef);
```

File: packages/component/src/hooks/internal/useInjectStyles.ts [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+    if (stylesRoot && styles?.length) {
+      for (const style of styles) {
+        const isAddedToTheDOM = !!style.parentNode;
+        const isAddedToTheRoot = style.parentNode === stylesRoot;
+        // We use the passed style node, but:
+        // if it's already added to the same root, we only add a ref to it into `injectedStyleRefs`
+        // if it's already added to the different root. we clone the style node and add it to the new root
+        const injectedStyle = isAddedToTheDOM && !isAddedToTheRoot ? (style.cloneNode() as HTMLStyleElement) : style;
+        // Update nonce in case it got changed
+        nonce && injectedStyle.setAttribute('nonce', nonce);
```
Comment (OEvgeny) [inline packages/component/src/hooks/internal/useInjectStyles.ts:21]:
```suggestion
        nonce ? injectedStyle.setAttribute('nonce', nonce) : injectedStyle.removeAttribute('nonce');
```

File: packages/component/src/hooks/internal/useInjectStyles.ts [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+        const isAddedToTheRoot = style.parentNode === stylesRoot;
+        // We use the passed style node, but:
+        // if it's already added to the same root, we only add a ref to it into `injectedStyleRefs`
+        // if it's already added to the different root. we clone the style node and add it to the new root
+        const injectedStyle = isAddedToTheDOM && !isAddedToTheRoot ? (style.cloneNode() as HTMLStyleElement) : style;
+        // Update nonce in case it got changed
+        nonce ? injectedStyle.setAttribute('nonce', nonce) : injectedStyle.removeAttribute('nonce');
+        if (!isAddedToTheRoot) {
+          stylesRoot.appendChild(injectedStyle);
+        }
```
[the remark this answers is not in the document]
Comment (OEvgeny) [reply packages/component/src/hooks/internal/useInjectStyles.ts:24]: The `CSSStyleDeclaration` cannot be used to pass stylesheets. It's dedicated to the single element styles.  We could probably utilize the new [`CSSStyleSheet`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/CSSStyleSheet) for injecting styles into shadow roots, but it is harder to follow and debug. Styles injected this way are not visible in the DOM. Refer to this [pen](https://codepen.io/Overrideveloper/pen/zXBqOG) to try it yourself.

We do need to clone style tags as each of roots should contain a copy of the style. We could probably pass CSS as a text, but this seems not safe, nor ergonomic API-wise.

If you don't like the fact we both use the passed styles, and cloned styles in the DOM, we could just use cloned ones regardless the parent of the passed style presence.

Note that implemented approach allows mitigating duplicate styles for the style refs passed. As we don't keep track of the relation of the styles already cloned to the passed ones, there are still cases when we may add duplicate styles.

File: packages/component/tsup.config.ts [hunk 9]
```diff
@@ -5,6 +5,6 @@ export default defineConfig({
   ...baseConfig,
   entry: {
     'botframework-webchat-component': './src/index.ts',
-    'botframework-webchat-component.internal': './src/internal.ts'
+    'botframework-webchat-component.internal': './src/internal.ts',
```
Comment (OEvgeny) [inline packages/component/tsup.config.ts:8]:
```suggestion
    'botframework-webchat-component.internal': './src/internal.ts'
```

File: packages/component/src/BasicToaster.js [hunk 10]
```diff
@@ -9,9 +9,9 @@ import CollapseIcon from './Toast/CollapseIcon';
 import ExpandIcon from './Toast/ExpandIcon';
 import NotificationIcon from './Toast/NotificationIcon';
 import randomId from './Utils/randomId';
-import useInternalRenderMarkdownInline from './hooks/internal/useInternalRenderMarkdownInline';
-import useStyleToEmotionObject from './hooks/internal/useStyleToEmotionObject';
 import useStyleSet from './hooks/useStyleSet';
+import { useStyleToEmotionObject } from './hooks/internal/styleToEmotionObject';
+import useInternalRenderMarkdownInline from './hooks/internal/useInternalRenderMarkdownInline';
```
Comment (OEvgeny) [inline packages/component/src/BasicToaster.js:14]:
```suggestion
import { useStyleToEmotionObject } from './hooks/internal/styleToEmotionObject';
import useInternalRenderMarkdownInline from './hooks/internal/useInternalRenderMarkdownInline';
import useStyleSet from './hooks/useStyleSet';
```

File: packages/component/package.json [hunk 11]
```diff
@@ -40,7 +40,7 @@
   },
   "files": [
     "./dist/**/*",
-    "./internal.js",
+    "./internal/*.js",
```
Comment (OEvgeny) [inline packages/component/package.json:43]:
```suggestion
    "./*.js",
```

File: packages/api/src/StyleOptions.ts [hunk 12]
```diff
@@ -872,6 +872,13 @@ type StyleOptions = {
    * @default 2000
    */
   maxMessageLength?: number;
+
+  /**
+   * The node used for WebChat styles to be placed into
```
Comment (compulim) [inline packages/api/src/StyleOptions.ts:877]:
```suggestion
   * The node to place Web Chat styles into. Needed when using as a Web Component.
```

File: packages/component/src/internal.ts [hunk 13]
```diff
@@ -1,5 +1,6 @@
 import parseDocumentFromString from './Utils/parseDocumentFromString';
 import serializeDocumentIntoString from './Utils/serializeDocumentIntoString';
 import { useLiveRegion } from './providers/LiveRegionTwin/index';
+import useInjectStyles from './hooks/internal/useInjectStyles';
 
-export { parseDocumentFromString, serializeDocumentIntoString, useLiveRegion };
+export { useInjectStyles, parseDocumentFromString, serializeDocumentIntoString, useLiveRegion };
```
Comment (compulim) [inline packages/component/src/internal.ts:6]:
```suggestion
export { parseDocumentFromString, serializeDocumentIntoString, useInjectStyles, useLiveRegion };
```

**Review by compulim — APPROVED** [review]

**Review by compulim — APPROVED** [review]
