### PR TITLE
Fix create style set with ac

### LINKED ISSUE #1969: Move `styleSet` related to Adaptive Cards and rich cards to full bundle
Since we moved Adaptive Cards to full bundle, we should also move related `styleSet`.

Note:
- When user loading full bundle, they call `window.WebChat.createStyleSet`, this should produce a style set that include Adaptive Cards stuff
- When user loading minimal bundle, they call `window.WebChat.createStyleSet`, this should not produce a style set with Adaptive Cards specific stuff
- Please write a simple unit test to make sure we capture the notes above. No need visual regression test

### PR DESCRIPTION
**Pull request by corinagum**
Fixes #1969 

## Changelog Entry
- Fix [#1969](https://github.com/Microsoft/BotFramework-WebChat/issues/1969). Move `styleSet`s related to Adaptive Cards to full bundle, by [@corinagum](https://github.com/corinagum) in PR [#1987](https://github.com/Microsoft/BotFramework-WebChat/pull/1987)

## Description
Because Adaptive Cards have been moved to the full bundle, the styleSets also need to be moved. I missed this on the original PR.

- [x] Testing Added

### CODE REVIEW

File: packages/bundle/src/adaptiveCards/Attachment/CommonCard.js [hunk 1]
```diff
@@ -32,13 +32,15 @@ export default class CommonCard extends React.Component {
     return (
       <AdaptiveCardRenderer
         adaptiveCard={ content && this.buildCard(adaptiveCards, content) }
-        tapAction={ tap }
+        adaptiveCardHostConfig={ adaptiveCardHostConfig }
+        tapAction={ content && tap }
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Attachment/CommonCard.js]: Okay to keep it or not.

Currently, if `content` is falsy, `tap` will always be `undefined`. No need to worry about null reference exception here.

But your extra logic could also means, "no matter what changes in the future, if there is no content, the user cannot tap on it."

File: packages/bundle/src/adaptiveCards/Attachment/ThumbnailCardAttachment.js [hunk 2]
```diff
@@ -44,23 +44,25 @@ export default class ThumbnailCardAttachment extends React.Component {
...
+        attachment: { content } = {}
+      }
+    } = this;
 
     return (
       <AdaptiveCardRenderer
         adaptiveCard={ content && this.buildCard(adaptiveCards, content) }
-        tapAction={ tap }
+        adaptiveCardHostConfig={ adaptiveCardHostConfig }
+        tapAction={ content && content.tap }
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Attachment/ThumbnailCardAttachment.js]: Destructure `tap` from `content`?

File: packages/bundle/src/adaptiveCards/Styles/adaptiveCardHostConfig.js [hunk 3]
```diff
@@ -1,4 +1,4 @@
-import defaultStyleSetOptions from './defaultStyleSetOptions';
+import defaultStyleOptions from 'botframework-webchat-component/src/Styles/defaultStyleOptions';
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Styles/adaptiveCardHostConfig.js]: Don't reference it under `/src/`.

```suggestion
import { defaultStyleOptions } from 'botframework-webchat-component';
```

File: packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js [hunk 4]
```diff
@@ -0,0 +1,14 @@
+import createStyleSet from './createStyleSetWithAdaptiveCards';
+
+describe('createStyleSetWithAdaptiveCards', () => {
+
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js]: Remove empty line.

File: packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+  it('should contain adaptive card styles in createStyleSet', () => {
+    const { adaptiveCardRenderer, animationCardAttachment, audioCardAttachment} = createStyleSet();
+
+    expect(adaptiveCardRenderer).not.toBeFalsy();
+
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js]: Remove empty line.

File: packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+    expect(animationCardAttachment).not.toBeFalsy();
+
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js]: Remove empty line.

File: packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js [hunk 7]
```diff
@@ -0,0 +1,14 @@
+import createStyleSet from './createStyleSetWithAdaptiveCards';
+
+describe('createStyleSetWithAdaptiveCards', () => {
+
+  it('should contain adaptive card styles in createStyleSet', () => {
```
Comment (compulim) [inline packages/bundle/src/adaptiveCards/Styles/createStyleSetWithAdaptiveCards.spec.js]:
```suggestion
  it('should contain Adaptive Card styles in createStyleSet', () => {
```

File: packages/bundle/src/adaptiveCards/Attachment/CommonCard.js (hunk 1 above)
Comment (corinagum) [reply packages/bundle/src/adaptiveCards/Attachment/CommonCard.js]: this change was because of an eslint error. it says 'tap' is never used. Do you have a different recommendation?

Comment (compulim) [reply packages/bundle/src/adaptiveCards/Attachment/CommonCard.js]: image

It looks good on eslint.
