### PR TITLE
[Post 4.10.1] Fix suggested actions maxHeight

### LINKED ISSUE #3444: Suggested Actions container height is not flexible
I tried using the new style options to set height and overflow for the suggested actions container. It's always fixed height whereas we want it to be flexible so that max-height is what we want to set. The height should fit the content if the container have few buttons and doesn't overflow
styleOptions={{
              botAvatarInitials: true,
              userAvatarInitials: true,
              suggestedActionBackground: 'White',
              suggestedActionBorder: 0,
              suggestedActionBorderRadius: 4,
              suggestedActionBorderStyle: 'solid',
              suggestedActionBorderWidth: 1,
              suggestedActionHeight: 32,
              suggestedActionLayout: 'stacked',
              suggestedActionsStackedHeight: '50vh',
              suggestedActionsStackedOverflow: 'auto'
            }}

## Screenshots
stacked actions

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

### PR DESCRIPTION
**Pull request by corinagum**
> Fixes #3444

## Changelog Entry

-  Fixes [#3444](https://github.com/microsoft/BotFramework-WebChat/issues/3444). Make suggested actions container height styleOption flexible, by [@corinagum](https://github.com/corinagum) in PR [#XXX](https://github.com/microsoft/BotFramework-WebChat/pull/XXX)

## Description

Suggested Actions height was set to static, causing issues if assigned height was different than stacked height of all buttons. This fixes the height style option to be assigned to `maxHeight`

## Design

-  [x] I have added tests and executed them locally
-  [x] I have updated `CHANGELOG.md`
-  [x] I have updated documentation

## Review Checklist

> This section is for contributors to review your work.

-  [x] Accessibility reviewed (tab order, content readability, alt text, color contrast)
-  [x] Browser and platform compatibilities reviewed
-  [x] CSS styles reviewed (minimal rules, no `z-index`)
-  [x] Documents reviewed (docs, samples, live demo)
-  [x] Internationalization reviewed (strings, unit formatting)
-  [x] `package.json` and `package-lock.json` reviewed
-  [x] Security reviewed (no data URIs, check for nonce leak)
-  [x] Tests reviewed (coverage, legitimacy)

### CODE REVIEW

File: packages/component/src/Styles/StyleSet/SuggestedActions.js [hunk 1]
```diff
@@ -54,7 +54,8 @@ export default function createSuggestedActionsStyle({
       },
 
       '& .webchat__suggested-actions__stack': {
-        height: suggestedActionsStackedHeight || 'auto',
+        height: 'auto',
```
Comment (compulim) [inline packages/component/src/Styles/StyleSet/SuggestedActions.js:57]: I am not 100% if we need `height: auto` here. Can you check?

**Review by compulim — APPROVED** [review]
Looks good. Thanks for testing corner cases.

**Comment by compulim** [comment]
Please don't merge until after 4.10.1. 🙏🏻
